//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:2.0.50727.4952
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoulHunt.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoulHunt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;table class=&quot;content_table&quot;&gt;
        ///	&lt;tr class=&quot;grayed&quot;&gt;&lt;td&gt;[[NPC_NAME]] (&lt;a href=&quot;javascript:window.external.Navigate(&apos;NPC&apos;, &apos;[[NPC_ID]]&apos;)&quot;&gt;[[NPC_ID]]&lt;/a&gt;)&lt;/td&gt;&lt;/tr&gt;
        ///&lt;/table&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string dialog_npc_template {
            get {
                return ResourceManager.GetString("dialog_npc_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;table class=&quot;dialog_table&quot;&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;
        ///&lt;div class=&quot;dialog_text&quot;&gt;
        ///	&lt;p&gt;[[DIALOG_TEXT]]&lt;/p&gt;
        ///&lt;/div&gt;
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;br/&gt;
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string dialog_preview_element_template {
            get {
                return ResourceManager.GetString("dialog_preview_element_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;table class=&quot;dialog_table&quot;&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;
        ///&lt;div class=&quot;dialog_npc_name&quot;&gt;
        ///&lt;P&gt;NPC 이름&lt;/P&gt;
        ///&lt;/div&gt;
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///
        ///&lt;tr&gt;
        ///&lt;td&gt;
        ///[[DIALOG_TEXT_ELEMENT]]
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///
        ///&lt;tr&gt;
        ///&lt;td&gt;
        ///&lt;div class=&quot;dialog_text&quot;&gt;
        ///----------------------------------------------------------------------
        ///&lt;/div&gt;
        ///&lt;div class=&quot;dialog_select&quot;&gt;
        ///▶ 선택1&lt;br/&gt;
        ///▶ 선택2
        ///&lt;/div&gt;
        ///&lt;br/&gt;
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/table&gt;
        ///
        ///&lt;br/&gt;
        ///
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string dialog_preview_template {
            get {
                return ResourceManager.GetString("dialog_preview_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;h1&gt;[[DIALOG_TEXT]] (&lt;a href=&quot;javascript:window.external.CopyString(&apos;[[ID]]&apos;)&quot;&gt;[[ID]]&lt;/a&gt;)&lt;/h1&gt;
        ///
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string dialog_template {
            get {
                return ResourceManager.GetString("dialog_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;error&quot;&gt;
        ///	&lt;p&gt;이 컨텐츠는 에러를 포함하고 있습니다. 원본 파일을 수정 하시면 에러가 자동복구됩니다.&lt;/p&gt;
        ///	&lt;p&gt;[[Message]]&lt;/p&gt;
        ///&lt;/div&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string error_template {
            get {
                return ResourceManager.GetString("error_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;tr&gt;
        ///	&lt;td&gt;[[LOOT_DETAIL]]&lt;/td&gt;
        ///	&lt;td&gt;[[LOOT_RATE]]&lt;/td&gt;
        ///	&lt;td&gt;[[LOOT_MIN]]&lt;/td&gt;
        ///	&lt;td&gt;[[LOOT_MAX]]&lt;/td&gt;
        ///&lt;/tr&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string loot_element_template {
            get {
                return ResourceManager.GetString("loot_element_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;h2&gt;전리품 목록&lt;/h2&gt;
        ///
        ///&lt;ul&gt;
        ///	&lt;li&gt;아이디: &lt;a href=&quot;javascript:window.external.Navigate(&apos;LOOTING&apos;, &apos;[[LOOT_ID]]&apos;)&quot;&gt;[[LOOT_ID]]&lt;/a&gt;&lt;/li&gt;
        ///	&lt;li&gt;최대갯수: [[LOOT_MAX]]&lt;/li&gt;
        ///&lt;/ul&gt;
        ///
        ///&lt;table class=&quot;content_table&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;내용&lt;/th&gt;
        ///	&lt;th&gt;확률&lt;/th&gt;
        ///	&lt;th&gt;최소&lt;/th&gt;
        ///	&lt;th&gt;최대&lt;/th&gt;
        ///&lt;/tr&gt;
        ///	[[LOOT_ELEMENTS]]
        ///&lt;/table&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string loot_template {
            get {
                return ResourceManager.GetString("loot_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;table class=&quot;content_table&quot;&gt;
        ///	&lt;tr class=&quot;grayed&quot;&gt;&lt;td&gt;조건: [[Condition]]&lt;/td&gt;&lt;/tr&gt;
        ///	&lt;tr&gt;&lt;td&gt;[[Interaction]]&lt;/td&gt;&lt;/tr&gt;
        ///	&lt;tr&gt;&lt;td&gt;&lt;q&gt;&lt;span class=&quot;gray&quot;&gt;[[Details]]&lt;/span&gt;&lt;/q&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;/table&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string npc_interaction_template {
            get {
                return ResourceManager.GetString("npc_interaction_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;h1&gt;[[Name]][[Clan]] (&lt;a href=&quot;javascript:window.external.CopyString(&apos;[[ID]]&apos;)&quot;&gt;[[ID]]&lt;/a&gt;)&lt;/h1&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;타입: [[Type]]&lt;/li&gt;
        ///	&lt;li&gt;레벨: [[Level]]&lt;/li&gt;
        ///	&lt;li&gt;등급: [[Grade]]&lt;/li&gt;
        ///&lt;/ul&gt;
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string npc_template {
            get {
                return ResourceManager.GetString("npc_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;table class=&quot;content_table&quot;&gt;
        ///	&lt;tr class=&quot;grayed&quot;&gt;&lt;td&gt;[[NPC_NAME]] (&lt;a href=&quot;javascript:window.external.Navigate(&apos;NPC&apos;, &apos;[[NPC_ID]]&apos;)&quot;&gt;[[NPC_ID]]&lt;/a&gt;) , [[QUEST_TYPE]]&lt;/td&gt;&lt;/tr&gt;
        ///&lt;/table&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string quest_npc_template {
            get {
                return ResourceManager.GetString("quest_npc_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;table class=&quot;content_table&quot;&gt;
        ///	&lt;tr class=&quot;grayed&quot;&gt;&lt;td&gt;[[QUEST_OBJ_ID]] , [[QUEST_OBJ_DESC]]&lt;/td&gt;&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td&gt;
        ///			&lt;UL&gt;
        ///&lt;!--				&lt;LI&gt;type: [[QUEST_OBJ_TYPE]]&lt;/LI&gt; --&gt;
        ///				&lt;LI&gt;param1: [[QUEST_OBJ_PARAM1]]&lt;/LI&gt;
        ///				&lt;LI&gt;param2: [[QUEST_OBJ_PARAM2]]&lt;/LI&gt;
        ///&lt;!--				&lt;LI&gt;public_progress: [[QUEST_OBJ_PUBLIC_PROGRESS]]&lt;/LI&gt; --&gt;
        ///				&lt;LI&gt;field: [[QUEST_OBJ_FIELD]]&lt;/LI&gt;
        ///				&lt;LI&gt;marker: [[QUEST_OBJ_MARKER]]&lt;/LI&gt;
        ///			&lt;/UL&gt;
        ///		&lt;/TD&gt;
        ///	&lt;/TR&gt;
        ///&lt;/table&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string quest_objective_template {
            get {
                return ResourceManager.GetString("quest_objective_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;table class=&quot;dialog_table&quot;&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;
        ///&lt;div class=&quot;dialog_npc_name&quot;&gt;
        ///&lt;P&gt;NPC 이름&lt;/P&gt;
        ///&lt;/div&gt;
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///
        ///&lt;tr&gt;
        ///&lt;td&gt;
        ///[[DIALOG_TEXT_ELEMENT]]
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///
        ///&lt;tr&gt;
        ///&lt;td&gt;
        ///&lt;div class=&quot;dialog_text&quot;&gt;
        ///----------------------------------------------------------------------
        ///&lt;/div&gt;
        ///&lt;div class=&quot;dialog_select&quot;&gt;
        ///▶ 선택1&lt;br/&gt;
        ///▶ 선택2
        ///&lt;/div&gt;
        ///&lt;br/&gt;
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/table&gt;
        ///
        ///&lt;br/&gt;
        ///
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string quest_preview_template {
            get {
                return ResourceManager.GetString("quest_preview_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;table class=&quot;content_table&quot;&gt;
        ///	&lt;tr class=&quot;grayed&quot;&gt;&lt;td&gt;[[QUEST_OBJ_ID]] , [[QUEST_OBJ_DESC]]&lt;/td&gt;&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td&gt;
        ///			&lt;UL&gt;
        ///&lt;!--				&lt;LI&gt;type: [[QUEST_OBJ_TYPE]]&lt;/LI&gt; --&gt;
        ///				&lt;LI&gt;param1: [[QUEST_OBJ_PARAM1]]&lt;/LI&gt;
        ///				&lt;LI&gt;param2: [[QUEST_OBJ_PARAM2]]&lt;/LI&gt;
        ///&lt;!--				&lt;LI&gt;public_progress: [[QUEST_OBJ_PUBLIC_PROGRESS]]&lt;/LI&gt; --&gt;
        ///				&lt;LI&gt;field: [[QUEST_OBJ_FIELD]]&lt;/LI&gt;
        ///				&lt;LI&gt;marker: [[QUEST_OBJ_MARKER]]&lt;/LI&gt;
        ///			&lt;/UL&gt;
        ///		&lt;/TD&gt;
        ///	&lt;/TR&gt;
        ///&lt;/table&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string quest_reward_template {
            get {
                return ResourceManager.GetString("quest_reward_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;h1&gt;[[QUEST_TEXT]] (&lt;a href=&quot;javascript:window.external.CopyString(&apos;[[ID]]&apos;)&quot;&gt;[[ID]]&lt;/a&gt;)&lt;/h1&gt;
        ///
        ///[[QUEST_NPCS]]
        ///
        ///[[QUEST_OBJECTIVES]]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string quest_template {
            get {
                return ResourceManager.GetString("quest_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div&gt;
        ///	&lt;h1&gt;Velixian [[PRODUCT_VERSION]] 변경사항&lt;/h1&gt;
        ///	&lt;ul&gt;
        ///		&lt;li&gt;&lt;span class=&quot;warning&quot;&gt;대화 미리보기 기능을 추가하였습니다.(2011/03/11)&lt;/span&gt;&lt;/li&gt;
        ///		&lt;li&gt;&lt;span class=&quot;warning&quot;&gt;창에 도킹 기능을 추가하였습니다.(2011/03/06)&lt;/span&gt;&lt;/li&gt;
        ///		
        ///&lt;!--		
        ///		&lt;li&gt;조건 편집의 타입에 &apos;quest_objective_complete&apos;, &apos;quest_objective_incomplete&apos;을 사용할 수 있게 되었습니다.&lt;/li&gt;
        ///		&lt;li&gt;퀘스트 편집의 타입에 &apos;SCOUT&apos;를 사용할 수 있게 되었습니다.&lt;/li&gt;
        ///		&lt;li&gt;&lt;span class=&quot;warning&quot;&gt;이제 조건을 편집하고 저장할 수 있습니다.&lt;/span&gt;&lt;/li&gt;
        ///		&lt;li&gt;&lt;span class=&quot;warning&quot;&gt;문자열 검색이 보다 개선되었습니다. (검색 옵션이 늘어났습니다.)&lt;/span&gt;
        ///			&lt;ul&gt;
        ///		[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot; &quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
        ///&lt;html xml:lang=&quot;ko&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;.&lt;/title&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body { background-color: #fff; color: #303030; padding: 5px; margin: 0; font-family: &quot;돋움&quot;; font-size: 12px; line-height: 1.5em; }
        ///			h1 { font-size: 16px; font-weight: bold; color: #0072bc; width: 100%; border-bottom: 2px[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string xhtml_template {
            get {
                return ResourceManager.GetString("xhtml_template", resourceCulture);
            }
        }
    }
}
