#ifndef _MMONITORSTRINGDEFINE
#define _MMONITORSTRINGDEFINE


// string.xml의 아이디 정의.
#define MNTS_PROCESS_RUN			"PROCESS_RUN"
#define MNTS_PROCESS_DOWN			"PROCESS_DOWN"
#define MNTS_DB_CONNECT				"DATABASE_CONNECT"
#define MNTS_DB_DISCONNECT			"DATABASE_DISCONNECT"
#define MNTS_RUN_TIME				"RUN_TIME"
#define MNTS_USER_CONNECTION		"USER_CONNECTION"
#define MNTS_CPU_PERFORMANCE		"CPU_PERFORMANCE"
#define MNTS_MEMORY_PERFORMANCE		"MEMORY_PERFORMANCE"
#define MNTS_DISK_PERFORMANCE		"DISK_PERFORMANCE"



#endif