//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Plugin_SoulHunt.rc
//
#define IDOK_ZONE                       3
#define IDCANCEL_ZONE                   4
#define IDD_VL_MAP_NEW                  140
#define IDD_VR_ENTITY_ENVIRONMENT       174
#define IDD_VR_ENTITY_OBJ_LIST          194
#define IDD_DIALOG_INPUT_SENSOR_WARP    196
#define IDD_VR_ETC_PATH_FIND            202
#define IDR_MENU_NEW_ENTITY             209
#define IDD_VR_ENTITY_MATERIAL          211
#define IDC_RADIO_IMPORT_SCENE          1006
#define IDC_BUTTON_IMPORT_SCENE_FIND    1016
#define IDC_BUTTON_NEW_SPAWN            1016
#define IDC_BUTTON_PATH_RESET           1016
#define IDC_BUTTON_BASE_TILE_FIND       1017
#define IDC_BUTTON_NEW_MARKER           1017
#define IDC_BUTTON_PATH_CREATE          1017
#define IDC_BUTTON_NEW_SENSOR           1018
#define IDC_BUTTON_NEW_SPAWN_MAP_OBJ    1019
#define IDC_BUTTON_NEW_SPAWN_GATHER     1020
#define IDC_BUTTON_NEW_AREA             1021
#define IDC_BUTTON_NEW_AREA2            1022
#define IDC_BUTTON_NEW_ROOM             1022
#define IDC_EDIT_IMPORT_SCENE           1094
#define IDC_EDIT_NEW_X                  1112
#define IDC_EDIT_SUN                    1112
#define IDC_EDIT_SENSOR_QUEST           1112
#define IDC_EDIT_PATH_HRANGE            1112
#define IDC_EDIT_NEW_Y                  1113
#define IDC_EDIT_CLD                    1113
#define IDC_EDIT_PICK_MINX              1113
#define IDC_EDIT_RNY                    1114
#define IDC_EDIT_PICK_MAXX              1114
#define IDC_EDIT_NEW_XQ                 1115
#define IDC_EDIT_HRN                    1115
#define IDC_EDIT_PICK_MINY              1115
#define IDC_EDIT_NEW_YQ                 1116
#define IDC_EDIT_SNW                    1116
#define IDC_LIST_SEED_LIST              1116
#define IDC_EDIT_HSW                    1117
#define IDC_EDIT_MAXY                   1117
#define IDC_EDIT_PICK_MAXY              1117
#define IDC_EDIT_BASE_TILE              1119
#define IDC_RADIO_TEMPLATE              1151
#define IDC_RADIO_SUN                   1151
#define IDC_RADIO_CLD                   1152
#define IDC_RADIO_RNY                   1153
#define IDC_RADIO_HRN                   1154
#define IDC_RADIO_SNW                   1155
#define IDC_RADIO_HSW                   1156
#define IDC_RADIO_CLR                   1157
#define IDC_CHECK_VIEW_NPC              1160
#define IDC_CHECK_ACTIVE_NAVI           1160
#define IDC_CHECK_HIDE_SPAWN_HANDLER    1167
#define IDC_CHECK_VIEW_MAP_OBJ_HANDLER  1170
#define IDC_STATIC_SEPER_5              1206
#define IDC_STATIC_NEW_MAP_SIZE         1235
#define IDC_STATIC_NEW_MAP_DETAIL       1236
#define IDC_RADIO_600                   1237
#define IDC_RADIO_800                   1238
#define IDC_RADIO_CUSTOM                1239
#define IDC_RADIO_256                   1240
#define IDC_RADIO_512                   1241
#define IDC_RADIO_CUSTOM2               1242
#define IDC_STATIC_DISPLACE_PLACE       1243
#define IDC_STATIC_DISPLACE_PLACE2      1244
#define IDC_STATIC_ZONE_ID              1247
#define IDC_STATIC_ZONE_ID2             1248
#define IDC_BUTTON_ELEMENT_ADD          1248
#define IDC_BUTTON_PATH_FIND            1248
#define IDC_BUTTON_ELEMENT_DEL          1249
#define IDC_BUTTON_SAVE_PICKINGZ        1249
#define IDC_BUTTON_SCRIPT_EDIT          1251
#define IDC_NEW_ZONE                    1252
#define IDC_FROM_ZONE                   1253
#define IDC_FROM_FIELD                  1254
#define IDC_LIST_MAP_CANDI              1256
#define IDC_STATIC_ZONE_GROUP           1257
#define IDC_STATIC_ZONE_GROUP2          1258
#define IDC_COMBO_ZONE_ID               1259
#define IDC_COMBO_FIELD_ID              1260
#define IDC_BUTTON_FIELD_MANAGER        1262
#define IDC_BUTTON_NEW_SOUND            1272
#define IDC_BUTTON_DEL_SEL_SEED         1272
#define IDC_STATIC_GROUP_WEATHER        1355
#define IDC_STATIC_DEFAULT_WEATHER      1356
#define IDC_STATIC_GROUP_SOUND          1360
#define IDC_COMBO_ENTITY_ENV_SET        1366
#define IDC_EDIT_CLR                    1367
#define IDC_RADIO_FIND_TEST             1373
#define IDC_RADIO_FIND_SEED             1374
#define IDC_TREE_ENTITY_LIST_PREVIEW    1378
#define IDC_ENTITY_EDIT_LIST            1379
#define IDC_SPAWN_LIST                  1380
#define IDC_MARKER_LIST                 1381
#define IDC_SENSOR_LIST                 1382
#define IDC_CHECK_INVISIBLE_SPAWN       1383
#define IDC_CHECK_INVISIBLE_MARKER      1384
#define IDC_CHECK_INVISIBLE_SENSOR      1385
#define IDC_CHECK_SPAWN                 1386
#define IDC_CHECK_MARKER                1387
#define IDC_CHECK_SENSOR                1388
#define IDC_CHECK_SOUND                 1389
#define IDC_CHECK_INVISIBLE_SOUND       1390
#define IDC_SENSOR_LIST2                1391
#define IDC_ENTITY_AREA                 1392
#define IDC_CHECK_SOUND2                1393
#define IDC_CHECK_AREA                  1393
#define IDC_CHECK_INVISIBLE_AREA        1394
#define IDC_SPAWN_GRPOUP                1395
#define IDC_CHECK_AREA2                 1396
#define IDC_CHECK_ROOM                  1396
#define IDC_CHECK_INVISIBLE_ROOM        1397
#define IDC_STATIC_START                1449
#define IDC_STATIC_END                  1450
#define IDC_STATIC_START2               1450
#define IDC_EDIT_START_X                1451
#define IDC_STATIC_START3               1451
#define IDC_EDIT_START_Y                1452
#define IDC_STATIC_START4               1452
#define IDC_EDIT_START_Z                1453
#define IDC_EDIT_END_X                  1454
#define IDC_EDIT_END_Y                  1455
#define IDC_EDIT_END_Z                  1456
#define IDC_EDIT_PATH_VRANGE            1477
#define IDC_STATIC_FOR_NEW_ENTITY       1478
#define IDC_STATIC_ENTITY_HANDLER       1479
#define IDC_STATIC_NPC_OPER2            1480
#define IDC_STATIC_FIND_TEST            1481
#define IDC_STATIC_FIND_TEST2           1482
#define IDC_STATIC_FIND_TEST3           1483
#define IDC_EDIT_SENSOR_CONDITION       1484
#define IDC_STATIC_NAME_CONDITION       1485
#define IDC_STATIC_NAME_FIELD           1486
#define IDC_EDIT_SENSOR_FIELD           1487
#define IDC_BUTTON_OPEN_FIELD_MGR       1488
#define IDC_STATIC_NAME_MARKER          1489
#define IDC_EDIT_SENSOR_MARKER          1490
#define IDC_STATIC_NAME_TITLE           1491
#define IDC_EDIT_SENSOR_TITLE           1492
#define IDC_COMBO_BGM                   1494
#define IDC_COMBO_SENSOR_GATE_TYPE      1494
#define IDC_EDIT_SENSOR_FIELD_GROUP     1497
#define IDC_BUTTON_OPEN_FIELD_GROUP_MGR 1498
#define IDC_STATIC_NAME_FIELD_GROUP     1499
#define IDC_STATIC_NAME_GATE_TYPE       1546
#define IDC_STATIC_NAME_QUEST           1547
#define IDC_STATIC_SHARED_GROUP         1548
#define IDC_STATIC_TRIAL_GROUP          1549
#define IDC_RADIO_SHARED_WARP_TYPE      1551
#define IDC_RADIO_TRIAL_WARP_TYPE       1552
#define IDD_DIALOG_NEW_MINI_MAP         3000
#define IDC_CHECK_CL2_RENDER            3000
#define IDC_DEFAULT_BGM_BUTTON          3001
#define IDD_VR_ENV_FIELDINFO            3001
#define IDC_EDIT_SECTOR_HEIGHT          3002
#define IDC_EDIT_MIN_X                  3003
#define IDC_BUTTON_CLEAR                3004
#define IDC_BUTTON_APPLY                3005
#define IDC_EDIT_MAX_X                  3006
#define IDC_EDIT_MIN_Y                  3007
#define IDC_EDIT_MAX_Y                  3008
#define IDC_BUTTON_SETZONESIZE          3009
#define IDC_EDIT_AGGRO_Z                3010
#define IDC_CHECK_PICKING_AREA          3010
#define IDC_BUTTON_APPLY_AGGROZ         3011
#define IDC_BUTTON_AGGROZ_APPLY         3011
#define IDC_EDIT_SEARCH_LIST            3011
#define IDC_BUTTON_SEARCH               3012
#define IDC_FIXEDTIME_COMBO             3013
#define IDC_BUTTON_NPC_RELOAD           3019
#define ID_NEW_SPAWN                    32983
#define ID_NEW_MARKER                   32984
#define ID_NEW_SENSOR                   32985
#define ID_NEW_SOUND                    33003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3001
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3014
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
