#include "stdafx.h"
#include "MColorTable.h"

namespace mint3 {

//////////////////////////////////////////////////////////////////////////

MCOLOR MColorTable::NORMAL = MCOLOR(DEFCOLOR_NORMAL);
MCOLOR MColorTable::LIGHT = MCOLOR(DEFCOLOR_LIGHT);
MCOLOR MColorTable::DARK = MCOLOR(DEFCOLOR_DARK);
MCOLOR MColorTable::DISABLE = MCOLOR(DEFCOLOR_DISABLE);
MCOLOR MColorTable::BACKGROUND = MCOLOR(DEFCOLOR_BACKGROUND);

MCOLOR MColorTable::PEN_HIGHLIGHT = MCOLOR(DEFCOLOR_PEN_HIGHLIGHT);

// Frame Default
MCOLOR MColorTable::FRAME_PLANE = MCOLOR(DEFCOLOR_FRAME_PLANE);
MCOLOR MColorTable::FRAME_OUTLINE = MCOLOR(DEFCOLOR_FRAME_OUTLINE);
MCOLOR MColorTable::FRAME_TEXT = MCOLOR(DEFCOLOR_FRAME_TEXT);


// MLabel
MCOLOR MColorTable::MLABEL_TEXT = MCOLOR(DEFCOLOR_MLABEL_TEXT);

// MButton
MCOLOR MColorTable::MBUTTON_PLANE = MCOLOR(DEFCOLOR_MBUTTON_PLANE);
MCOLOR MColorTable::MBUTTON_LIGHTPLANE = MCOLOR(DEFCOLOR_MBUTTON_LIGHTPLANE);
MCOLOR MColorTable::MBUTTON_DARKPLANE = MCOLOR(DEFCOLOR_MBUTTON_DARKPLANE);
MCOLOR MColorTable::MBUTTON_TEXT = MCOLOR(DEFCOLOR_MBUTTON_TEXT);


// MEdit
MCOLOR MColorTable::MEDIT_PLANE = MCOLOR(DEFCOLOR_MEDIT_PLANE);
MCOLOR MColorTable::MEDIT_OUTLINE = MCOLOR(DEFCOLOR_MEDIT_OUTLINE);
MCOLOR MColorTable::MEDIT_TEXT = MCOLOR(DEFCOLOR_MEDIT_TEXT);


// MList
MCOLOR MColorTable::MLIST_PLANE = MCOLOR(DEFCOLOR_MLIST_PLANE);
MCOLOR MColorTable::MLIST_OUTLINE = MCOLOR(DEFCOLOR_MLIST_OUTLINE);
MCOLOR MColorTable::MLIST_SELECTEDPLANE = MCOLOR(DEFCOLOR_MLIST_SELECTEDPLANE);
MCOLOR MColorTable::MLIST_TEXT = MCOLOR(DEFCOLOR_MLIST_TEXT);
MCOLOR MColorTable::MLIST_SELECTEDTEXT = MCOLOR(DEFCOLOR_MLIST_SELECTEDTEXT);
MCOLOR MColorTable::MLIST_UNFOCUSED_SELECTED_PLANE = MCOLOR(DEFCOLOR_DARK);

// MScollBar
MCOLOR MColorTable::MSCROLLBAR_PLANE = MCOLOR(DEFCOLOR_MSCROLLBAR_PLANE);

// MPopup
MCOLOR MColorTable::MPOPUP_PLANE = MCOLOR(DEFCOLOR_MPOPUP_PLANE);
MCOLOR MColorTable::MPOPUP_SELECTEDPLANE = MCOLOR(DEFCOLOR_MPOPUP_SELECTEDPLANE);
MCOLOR MColorTable::MPOPUP_TEXT = MCOLOR(DEFCOLOR_MPOPUP_TEXT);
MCOLOR MColorTable::MPOPUP_SELECTEDTEX = MCOLOR(DEFCOLOR_MPOPUP_SELECTEDTEXT);


// ToolTip
MCOLOR MColorTable::MTOOLTIP_PLANE = MCOLOR(DEFCOLOR_MTOOLTIP_PLANE);
MCOLOR MColorTable::MTOOLTIP_OUTLINE = MCOLOR(DEFCOLOR_MTOOLTIP_OUTLINE);
MCOLOR MColorTable::MTOOLTIP_TEXT = MCOLOR(DEFCOLOR_MTOOLTIP_TEXT);


// MFrame
MCOLOR MColorTable::MFRAME_PLANE = MCOLOR(DEFCOLOR_MFRAME_PLANE);
MCOLOR MColorTable::MFRAME_OUTLINE = MCOLOR(DEFCOLOR_MFRAME_OUTLINE);
MCOLOR MColorTable::MMENUBAR_PLANE = MCOLOR(DEFCOLOR_MMENUBAR_PLANE);
MCOLOR MColorTable::MMENUBAR_TEXT = MCOLOR(DEFCOLOR_MMENUBAR_TEXT);

// MPanel
MCOLOR MColorTable::MPANEL_PLANE = MCOLOR(DEFCOLOR_MPANEL_PLANE);
MCOLOR MColorTable::MPANEL_BORDER = MCOLOR(DEFCOLOR_MPANEL_BORDER);

// TextArea
MCOLOR MColorTable::TEXTAREA_TEXT = MCOLOR(DEFCOLOR_TEXTAREA_TEXT);
MCOLOR MColorTable::TEXTAREA_PLANE = MCOLOR(DEFCOLOR_TEXTAREA_PLANE);
MCOLOR MColorTable::TEXTAREA_OUTLINE = MCOLOR(DEFCOLOR_TEXTAREA_OUTLINE);


} // namespace mint3