// Default Widget Color
#pragma once

namespace mint3 {

#define DEFCOLOR_NORMAL			0xFF4499FF

#define DEFCOLOR_LIGHT			0xFF77BBFF
#define DEFCOLOR_DARK			0xFF2266FF
#define DEFCOLOR_DISABLE		0xFF808080
#define DEFCOLOR_BACKGROUND		0xFF000000

#define DEFCOLOR_PEN_HIGHLIGHT	0xFFFFFFFF

	// Frame Default
#define DEFCOLOR_FRAME_PLANE		DEFCOLOR_BACKGROUND
#define DEFCOLOR_FRAME_OUTLINE		DEFCOLOR_NORMAL
#define DEFCOLOR_FRAME_TEXT			0xFFFFFFFF

	// MLabel
#define DEFCOLOR_MLABEL_TEXT			0xFFFFFFFF

	// MButton
#define DEFCOLOR_MBUTTON_PLANE		DEFCOLOR_NORMAL
#define DEFCOLOR_MBUTTON_LIGHTPLANE	DEFCOLOR_LIGHT
#define DEFCOLOR_MBUTTON_DARKPLANE	DEFCOLOR_DARK
#define DEFCOLOR_MBUTTON_TEXT		0xFF000000

	// MEdit
#define DEFCOLOR_MEDIT_PLANE		DEFCOLOR_FRAME_PLANE
#define DEFCOLOR_MEDIT_OUTLINE		DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_MEDIT_TEXT			0xFFCDCDCD


	// MList
#define DEFCOLOR_MLIST_PLANE			0xFF141414
#define DEFCOLOR_MLIST_OUTLINE			DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_MLIST_SELECTEDPLANE	DEFCOLOR_MLIST_OUTLINE
#define DEFCOLOR_MLIST_TEXT				0xFFCDCDCD
#define DEFCOLOR_MLIST_SELECTEDTEXT		DEFCOLOR_MLIST_PLANE

	// MScollBar
#define DEFCOLOR_MSCROLLBAR_PLANE		0xFF000000

	// MPopup
#define DEFCOLOR_MPOPUP_PLANE			DEFCOLOR_FRAME_PLANE
#define DEFCOLOR_MPOPUP_SELECTEDPLANE	DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_MPOPUP_TEXT			DEFCOLOR_FRAME_TEXT
#define DEFCOLOR_MPOPUP_SELECTEDTEXT	DEFCOLOR_MPOPUP_PLANE

	// ToolTip
#define DEFCOLOR_MTOOLTIP_PLANE			DEFCOLOR_FRAME_PLANE
#define DEFCOLOR_MTOOLTIP_OUTLINE		DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_MTOOLTIP_TEXT			DEFCOLOR_FRAME_TEXT

	// MFrame
#define DEFCOLOR_MFRAME_PLANE			DEFCOLOR_FRAME_PLANE
#define DEFCOLOR_MFRAME_OUTLINE			DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_MMENUBAR_PLANE			DEFCOLOR_NORMAL
#define DEFCOLOR_MMENUBAR_TEXT			0xFF000000

	// MPanel
#define DEFCOLOR_MPANEL_PLANE			0x00000000
#define DEFCOLOR_MPANEL_BORDER			DEFCOLOR_NORMAL


	// TextArea
#define DEFCOLOR_TEXTAREA_TEXT			DEFCOLOR_MEDIT_TEXT
#define DEFCOLOR_TEXTAREA_PLANE			DEFCOLOR_MEDIT_PLANE
#define DEFCOLOR_TEXTAREA_OUTLINE		DEFCOLOR_MEDIT_OUTLINE



class MColorTable
{
public:
	static MCOLOR				NORMAL;
	static MCOLOR				LIGHT;
	static MCOLOR				DARK;
	static MCOLOR				DISABLE;
	static MCOLOR				BACKGROUND;

	static MCOLOR				PEN_HIGHLIGHT;

	// Frame Default
	static MCOLOR				FRAME_PLANE;
	static MCOLOR				FRAME_OUTLINE;
	static MCOLOR				FRAME_TEXT;

	// MLabel
	static MCOLOR				MLABEL_TEXT;

	// MButton
	static MCOLOR				MBUTTON_PLANE;
	static MCOLOR				MBUTTON_LIGHTPLANE;
	static MCOLOR				MBUTTON_DARKPLANE;
	static MCOLOR				MBUTTON_TEXT;

	// MEdit
	static MCOLOR				MEDIT_PLANE;
	static MCOLOR				MEDIT_OUTLINE;
	static MCOLOR				MEDIT_TEXT;

	// MList
	static MCOLOR				MLIST_PLANE;
	static MCOLOR				MLIST_OUTLINE;
	static MCOLOR				MLIST_SELECTEDPLANE;
	static MCOLOR				MLIST_TEXT;
	static MCOLOR				MLIST_SELECTEDTEXT;
	static MCOLOR				MLIST_UNFOCUSED_SELECTED_PLANE;

	// MScollBar
	static MCOLOR				MSCROLLBAR_PLANE;

	// MPopup
	static MCOLOR				MPOPUP_PLANE;
	static MCOLOR				MPOPUP_SELECTEDPLANE;
	static MCOLOR				MPOPUP_TEXT;
	static MCOLOR				MPOPUP_SELECTEDTEX;

	// ToolTip
	static MCOLOR				MTOOLTIP_PLANE;
	static MCOLOR				MTOOLTIP_OUTLINE;
	static MCOLOR				MTOOLTIP_TEXT;

	// MFrame
	static MCOLOR				MFRAME_PLANE;
	static MCOLOR				MFRAME_OUTLINE;

	// MenuBar
	static MCOLOR				MMENUBAR_PLANE;
	static MCOLOR				MMENUBAR_TEXT;

	// MPanel
	static MCOLOR				MPANEL_PLANE;
	static MCOLOR				MPANEL_BORDER;

	// TextArea
	static MCOLOR				TEXTAREA_TEXT;
	static MCOLOR				TEXTAREA_PLANE;
	static MCOLOR				TEXTAREA_OUTLINE;
};


} // namespace mint3