#pragma once

// 채팅 커맨드 ID - chatcmds.xml 에서 사용하는 ID

enum XChatCmdID
{
	CCMD_ID_HELP						= 1,
	CCMD_ID_DIE							= 2,
	CCMD_ID_AFK							= 3,


	CCMD_ID_SAY							= 10,
	CCMD_ID_TELL						= 11,
	CCMD_ID_REPLY						= 12,
	CCMD_ID_PARTY						= 13,
	CCMD_ID_GUILD						= 14,
	CCMD_ID_SHOUT						= 15,
	CCMD_ID_AUCTION						= 16,
	CCMD_ID_CHANNEL						= 17,
	CCMD_ID_FIELD						= 18,
	CCMD_ID_GLOBAL						= 19,
	CCMD_ID_NARRATION					= 20,
	CCMD_ID_ANNOUNCE					= 21,
	CCMD_ID_NOTICE						= 22,

	CCMD_ID_JOIN						= 30,
	CCMD_ID_LEAVE						= 31,
	CCMD_ID_KICK						= 32,
	CCMD_ID_BAN							= 33,
	CCMD_ID_UNBAN						= 34,
	CCMD_ID_OWNER						= 35,
	CCMD_ID_CREATE						= 36,

	CCMD_ID_SOCIAL_MOTION_BEG			= 100,
	CCMD_ID_SOCIAL_MOTION_BOW			= 101,
	CCMD_ID_SOCIAL_MOTION_CHEER			= 102,
	CCMD_ID_SOCIAL_MOTION_CLAP			= 103,
	CCMD_ID_SOCIAL_MOTION_CRY			= 104,
	CCMD_ID_SOCIAL_MOTION_DANCE			= 105,
	CCMD_ID_SOCIAL_MOTION_IGNORE		= 106,
	CCMD_ID_SOCIAL_MOTION_KISS			= 107,
	CCMD_ID_SOCIAL_MOTION_LAUGH			= 108,
	CCMD_ID_SOCIAL_MOTION_LOOKAROUND	= 109,
	CCMD_ID_SOCIAL_MOTION_NEGATIVE		= 110,
	CCMD_ID_SOCIAL_MOTION_POINT			= 111,
	CCMD_ID_SOCIAL_MOTION_POSITIVE		= 112,
	CCMD_ID_SOCIAL_MOTION_SALUTE		= 113,
	CCMD_ID_SOCIAL_MOTION_SIGH			= 114,
	CCMD_ID_SOCIAL_MOTION_TALK1			= 115,
	CCMD_ID_SOCIAL_MOTION_TALK2			= 116,
	CCMD_ID_SOCIAL_MOTION_TAUNT			= 117,
	CCMD_ID_SOCIAL_MOTION_WAVE			= 118,
	CCMD_ID_SOCIAL_MOTION_SIT			= 119,
	CCMD_ID_SOCIAL_MOTION_RISE			= 120,
};

