//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EffectTool.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_EffectToolTYPE              129
#define IDD_CONTROL_VIEW                130
#define IDC_LIST_EMITTER2               131
#define IDD_PAGE1                       132
#define IDD_EFFECT                      132
#define IDD_PAGE2                       133
#define IDD_MATERIAL                    133
#define IDD_PAGE3                       134
#define IDD_PARTICLE                    134
#define IDD_PAGE5                       136
#define IDD_EMITTER                     136
#define IDC_EFFECT_NAME                 1002
#define IDC_CHECK_SORTING               1003
#define IDC_BUTTON_ADD                  1004
#define IDC_BUTTON_DEL                  1005
#define IDC_BUTTON_LOAD                 1006
#define IDC_BUTTON_SAVE                 1007
#define IDC_EDIT_MAXCOUNT               1008
#define IDC_SLIDER_MAXPARTICLE          1009
#define IDC_EDIT_AMOUNT                 1010
#define IDC_SLIDER_AMOUNT               1011
#define IDC_EDIT_EMITLIFE               1012
#define IDC_SLIDER_EMITLIFE             1013
#define IDC_EDIT_ANGLE                  1014
#define IDC_SLIDER_ANGLE                1015
#define IDC_COMBO_TYPE                  1016
#define IDC_EDIT_DIRX                   1017
#define IDC_SPIN_DIRX                   1018
#define IDC_EDIT_DIRY                   1019
#define IDC_SPIN_DIRY                   1020
#define IDC_EDIT_DIRZ                   1021
#define IDC_SPIN_DIRZ                   1022
#define IDC_CHECK_RANDROT               1023
#define IDC_CHECK_ROTATION              1023
#define IDC_CHECK_WORLDAXIS             1024
#define IDC_CHECK_LOOPING               1025
#define IDC_EDIT_MINLIFE                1026
#define IDC_EDIT_MAXLIFE                1027
#define IDC_SLIDER_MINLIFE              1028
#define IDC_SLIDER_MAXLIFE              1029
#define IDC_EDIT_FOLDERNAME             1030
#define IDC_LIST_FILES                  1031
#define IDC_PICTURE_TEXTURE             1032
#define IDC_EDIT_TEXX                   1033
#define IDC_EDIT_TEXY                   1034
#define IDC_EDIT_TEXU                   1035
#define IDC_EDIT_TEXV                   1036
#define IDC_RADIO_ONE                   1037
#define IDC_RADIO_TWO                   1038
#define IDC_RADIO_THREE                 1039
#define IDC_COMBO_SRCBLEND              1040
#define IDC_COMBO_DESTBLEND             1041
#define IDC_BUTTON_FOLDER               1042
#define IDC_COMBO_DUMY                  1043
#define IDC_GRAPHICS                    1044
#define IDC_EDIT_TEXV2                  1044
#define IDC_EDIT_ALPHAREF               1044
#define IDC_SLIDER_TIME                 1045
#define IDC_LIST_TRACK                  1046
#define IDC_BUTTON_REMOVE               1048
#define IDC_BUTTON_UPDATE               1049
#define IDC_EDIT_TIME                   1050
#define IDC_EDIT_COLOR                  1051
#define IDC_EDIT_COLORA                 1052
#define IDC_EDIT_SCALE                  1053
#define IDC_EDIT_SCALEA                 1054
#define IDC_EDIT_MINVEL                 1055
#define IDC_EDIT_GRAVITY                1056
#define IDC_EDIT_SCALE2                 1057
#define IDC_EDIT_MAXVEL                 1058
#define IDC_SLIDER_MINVEL               1059
#define IDC_SLIDER_MAXVEL               1060
#define IDC_SLIDER_GRAVITY              1061
#define IDC_SLIDER_SCALE                1062
#define IDC_CHECK_COLOR_RAND            1063
#define IDC_CHECK_VEL_RAND              1064
#define IDC_EDIT_VELX                   1065
#define IDC_CHECK_GATHER                1065
#define IDC_EDIT_VELY                   1066
#define IDC_CHECK_EXPLOSION             1066
#define IDC_SPIN_VELX                   1067
#define IDC_SPIN_VELY                   1068
#define IDC_EDIT_VELZ                   1069
#define IDC_SPIN_VELZ                   1070
#define IDC_EDIT_POSX                   1071
#define IDC_SPIN_POSX                   1072
#define IDC_EDIT_POSY                   1073
#define IDC_SPIN_POSY                   1074
#define IDC_EDIT_POSZ                   1075
#define IDC_SPIN_POSZ                   1076
#define IDC_BUTTON_P1                   1077
#define IDC_BUTTON_P2                   1078
#define IDC_EDIT_WIND                   1079
#define IDC_EDIT_WDIRX                  1080
#define IDC_CHECK_MESHLOOPING           1081
#define IDC_SPIN_WDIRX                  1082
#define IDC_SLIDER1                     1083
#define IDC_EDIT_WDIRY                  1084
#define IDC_SLIDER_EMITTER_TIME         1085
#define IDC_SPIN_WDIRY                  1086
#define IDC_EDIT_MINRADIAN              1086
#define IDC_LIST_EMITTER_TRACK          1087
#define IDC_EDIT_WDIRZ                  1088
#define IDC_EDIT_MAXRADIAN              1088
#define IDC_EDIT_EMITTER_TIME           1089
#define IDC_SPIN_WDIRZ                  1090
#define IDC_SLIDER_MINRADIAN            1090
#define IDC_SLIDER_MAXRADIAN            1091
#define IDC_RADIO_BILLBOARD_XYZ         1092
#define IDC_RADIO_BILLBOARD_XY          1093
#define IDC_RADIO_PLANE_XY              1094
#define IDC_RADIO1                      1095
#define IDC_RADIO_SPREAD                1095
#define ID_FILE_OPEN_MESH               32771
#define ID_FILE_OPEN_ELU                32772
#define ID_VIEW_BGCOLOR                 32774
#define ID_VIEW_START                   32775
#define ID_VIEW_STOP                    32777
#define ID_TB_WIREFRAME                 32778
#define ID_TB_AXIS                      32779
#define ID_TB_GRID                      32780
#define ID_TB_EMITTER                   32781
#define ID_VIEW_PAUSE                   32783
#define ID_FILE_SAVEQ                   32784
#define ID_VIEW_PATH                    32785
#define ID_FILE_SAVEAS                  32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
