/// @file WM_USER
#pragma once

//윈도우 메시지
#define WM_USER_MULTISLIDER_CHANGED WM_USER + 2731 //2731쯤이면 난수가 될까?
#define WM_USER_REBAR_EXPANDED WM_USER_MULTISLIDER_CHANGED + 1
#define WM_USER_SIDEPANEL_EXPANDED WM_USER_REBAR_EXPANDED + 1
#define WM_USER_AUTOEDIT_VALID WM_USER_SIDEPANEL_EXPANDED + 1
#define WM_USER_WND_RESIZER_ENABLE WM_USER_AUTOEDIT_VALID + 1
#define WM_USER_WND_RESIZER_DISABLE WM_USER_WND_RESIZER_ENABLE + 1