#pragma once

// Network 관련 설정값

#define DEFAULT_MASTER_SERVER_PORT			7500
#define DEFAULT_LOGIN_SERVER_PORT			7501
#define DEFAULT_APPLICATION_SERVER_PORT		7502

#define DEFAULT_GAME_SERVER_PORT			7201

#define DEFAULT_LOCATOR_SERVER_PORT			7501	//	28901 네오위즈테스트
