#pragma once


/// 소셜 모션 타입
enum CSSocialMotionType
{
	SOCIAL_MOTION_BEG = 0,
	SOCIAL_MOTION_BOW,
	SOCIAL_MOTION_CHEER,
	SOCIAL_MOTION_CLAP,
	SOCIAL_MOTION_CRY,
	SOCIAL_MOTION_DANCE,
	SOCIAL_MOTION_IGNORE,
	SOCIAL_MOTION_KISS,
	SOCIAL_MOTION_LAUGH,
	SOCIAL_MOTION_LOOKAROUND,
	SOCIAL_MOTION_NEGATIVE,
	SOCIAL_MOTION_POINT,
	SOCIAL_MOTION_POSITIVE,
	SOCIAL_MOTION_SALUTE,
	SOCIAL_MOTION_SIGH,
	SOCIAL_MOTION_TALK1,
	SOCIAL_MOTION_TALK2,
	SOCIAL_MOTION_TAUNT,
	SOCIAL_MOTION_WAVE
};
