#pragma once

#define TALENT_XML_TAG_MAIET				"maiet"
#define TALENT_XML_TAG_TALENT				"TALENT"

// ATTR -------------------------------

#define TALENT_XML_ATTR_NAME				"name"
#define TALENT_XML_ATTR_NPC					"NPC"
#define TALENT_XML_ATTR_GUARD_CRASH_LEVEL	"GuardCrashLevel"
#define TALENT_XML_ATTR_PERFECTGUARDONLY	"PerfectGuardOnly"
#define TALENT_XML_ATTR_PARTIALGUARDHIT		"PartialGuardHit"
#define TALENT_XML_ATTR_CANCELABLE			"Cancelable"
#define TALENT_XML_ATTR_IGNORE_MESMERIZE		"IgnoreMesmerize"

#define TALENT_XML_ATTR_STANCE				"Stance"
#define TALENT_XML_ATTR_CATEGORY			"Category"
#define TALENT_XML_ATTR_DMGTYPE				"DamageType"
#define TALENT_XML_ATTR_TALENT_TYPE			"TalentType"
#define TALENT_XML_ATTR_STYLE				"Style"
#define TALENT_XML_ATTR_EXTRA_PASSIVE_TYPE	"ExtraPassive"
#define TALENT_XML_ATTR_EXTRA_PASSIVE_TYPE2	"ExtraPassive2"
#define TALENT_XML_ATTR_EXTRA_ACTIVE_TYPE	"ExtraActive"
#define TALENT_XML_ATTR_EXTRA_PASSIVE_PARAM	"ExtraPassiveParam"
#define TALENT_XML_ATTR_EXTRA_PASSIVE_PARAM2	"ExtraPassiveParam2"
#define TALENT_XML_ATTR_EXTRA_ACTIVE_PARAM1	"ExtraActiveParam1"
#define TALENT_XML_ATTR_EXTRA_ACTIVE_PARAM2	"ExtraActiveParam2"
#define TALENT_XML_ATTR_SKILL_TYPE			"SkillType"
#define TALENT_XML_ATTR_CRAFT_TYPE			"CraftType"
#define TALENT_XML_ATTR_IS_AIMING			"NPC_IsAiming"
#define TALENT_XML_ATTR_HITCAPSULEGROUPINDEX "NPC_HitCapsuleGroup"
#define TALENT_XML_ATTR_EXTRA_HITCAPSULEGROUP "ExtraHitCapsuleGroup"
#define TALENT_XML_ATTR_EXTRA_HITCAPSULEGROUP2 "ExtraHitCapsuleGroup2"
#define TALENT_XML_ATTR_EXTRA_HITCAPSULEGROUP3 "ExtraHitCapsuleGroup3"

#define TALENT_XML_ATTR_NEED_FOCUS			"NeedFocus"
#define TALENT_XML_ATTR_NEXT_FOCUS			"NextFocus"
#define TALENT_XML_ATTR_NPC_CHANGE_MODE		"NPCChangeMode"
#define TALENT_XML_ATTR_FINISH_EFFECT		"FinishEffect"

#define TALENT_XML_ATTR_BUFF					"Buff"
#define TALENT_XML_ATTR_BUFF_CONDITION			"BuffCondition"
#define TALENT_XML_ATTR_BUFF_EFFECT_RANGE		"BuffEffectRange"
#define TALENT_XML_ATTR_BUFF_RESIST_METHOD		"BuffResistMethod"
#define TALENT_XML_ATTR_BUFF_RESIST_TYPE		"BuffResistType"
#define TALENT_XML_ATTR_BUFF_RESIST_DIFFICULTY	"BuffResistDifficulty"

#define TALENT_XML_ATTR_EFFECT_POINT		"EffectPoint"

#define BUFF_XML_ATTR_EFFECT_TIMING			"EffectTiming"
#define BUFF_XML_ATTR_EFFECT_RANGE			"EffectRange"
#define BUFF_XML_ATTR_EFFECT_TARGET			"EffectTarget"
#define BUFF_XML_ATTR_EFFECT_LIMIT			"EffectLimit"

#define BUFF_XML_ATTR_RELEASE_CONDITION		"ReleaseCondition"
#define BUFF_XML_ATTR_RELEASE_PARAM			"ReleaseParam"

#define TALENT_XML_ATTR_DODGE_DIFFICULTY	"DodgeDifficulty"

#define TALENT_XML_ATTR_TALENTLINE			"TalentLine"
#define TALENT_XML_ATTR_COOLTIMELINE		"CooltimeLine"

#define TALENT_XML_ATTR_RANK				"Rank"
#define TALENT_XML_ATTR_UIINDIVIDUAL		"UIIndividual"

#define TALENT_XML_ATTR_COOLTIME			"CoolTime"

#define TALENT_XML_ATTR_AFFECTED_MOTION_SPEED	"AffectedMotionSpd"

#define TALENT_XML_ATTR_ITEM				"item"

#define TALENT_XML_ATTR_DESCRIPTION			"desc"

#define TALENT_XML_ATTR_REQUIRE_MOVESPEED	"RequireMoveSpeed"
#define TALENT_XML_ATTR_WEAPON_ALLOWED		"WeaponAllowed"

#define TALENT_XML_ATTR_UNTRAINABLE			"Untrainable"

#define TALENT_XML_TAG_NEED_TRAINING					"NeedTraining"
#define TALENT_XML_TAG_TNEED_LEVEL						"TNeed_Level"
#define TALENT_XML_TAG_TNEED_TALENT						"TNeed_Talent"
#define TALENT_XML_TAG_TNEED_STYLETP					"TNeed_StyleTP"
#define TALENT_XML_TAG_BYLICENSE						"ByLicense"

#define TALENT_XML_TAG_SWORD_TRAIL_EFFECT				"SwordTrailEffect"

#define TALENT_XML_TAG_MOVING_USE_TYPE					"MovingUseType"

#define TALENT_XML_ATTR_TARGETING_TYPE					"TargetType"
// VALUE ------------------------------------------------------------------------

#define TALENT_XML_VALUE_STANCE_ALL						"all"
#define TALENT_XML_VALUE_STANCE_NORMAL					"normal"
#define TALENT_XML_VALUE_STANCE_COMBAT					"combat"

#define TALENT_XML_VALUE_TALENTTYPE_SKILL				"skill"
#define TALENT_XML_VALUE_TALENTTYPE_WEAPON				"weapon"
#define TALENT_XML_VALUE_TALENTTYPE_ENCHANT				"enchant"
#define TALENT_XML_VALUE_TALENTTYPE_ITEM				"item"
#define TALENT_XML_VALUE_TALENTTYPE_CRAFT				"craft"
#define TALENT_XML_VALUE_TALENTTYPE_GROUP				"group"
#define TALENT_XML_VALUE_TALENTTYPE_GATHER				"gather"

#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_WEAPON_ONE_HANDED			"BASE_WEAPON_ONE_HANDED"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_WEAPON_1H_SLASH				"BASE_WEAPON_1H_SLASH"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_WEAPON_1H_BLUNT				"BASE_WEAPON_1H_BLUNT"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_WEAPON_1H_PIERCE				"BASE_WEAPON_1H_PIERCE"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_WEAPON_TWO_HANDED			"BASE_WEAPON_TWO_HANDED"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_WEAPON_STAFF					"BASE_WEAPON_STAFF"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_WEAPON_ARCHERY				"BASE_WEAPON_ARCHERY"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_WEAPON_2H_BLUNT				"BASE_WEAPON_2H_BLUNT"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_WEAPON_DUAL_PIERCE			"BASE_WEAPON_DUAL_PIERCE"

#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_WEAPON_GUN					"BASE_WEAPON_GUN"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_WEAPON_BOOK					"BASE_WEAPON_BOOK"

#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_WEAPON_SNEAK					"BASE_SNEAK"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_ELEMENTAL					"BASE_ELEMENTAL"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_HOLY							"BASE_HOLY"

#define TALENT_XML_VALUE_EXTRAPASSIVE_SPECIALIZATION_SLASH				"SPECIALIZATION_SLASH"
#define TALENT_XML_VALUE_EXTRAPASSIVE_SPECIALIZATION_BLUNT				"SPECIALIZATION_BLUNT"
#define TALENT_XML_VALUE_EXTRAPASSIVE_SPECIALIZATION_PIERCE				"SPECIALIZATION_PIERCE"
#define TALENT_XML_VALUE_EXTRAPASSIVE_SPECIALIZATION_ELEMENTAL			"SPECIALIZATION_ELEMENTAL"
#define TALENT_XML_VALUE_EXTRAPASSIVE_SPECIALIZATION_HOLY				"SPECIALIZATION_HOLY"

#define TALENT_XML_VALUE_EXTRAPASSIVE_UTILITY_SAFEFALL					"UTILITY_SAFEFALL"
#define TALENT_XML_VALUE_EXTRAPASSIVE_UTILITY_SAFEFALL2					"UTILITY_SAFEFALL2"

#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_ARMOR_LIGHT					"BASE_ARMOR_LIGHT"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_ARMOR_MEDIUM					"BASE_ARMOR_MEDIUM"
#define TALENT_XML_VALUE_EXTRAPASSIVE_BASE_ARMOR_HEAVY					"BASE_ARMOR_HEAVY"

#define TALENT_XML_VALUE_EXTRAPASSIVE_TALENT_SHOUT_RADIUS				"TALENT_SHOUT_RADIUS"
#define TALENT_XML_VALUE_EXTRAPASSIVE_TALENT_SAZAHU						"TALENT_SAZAHU"

#define TALENT_XML_VALUE_EXTRAPASSIVE_FOCUS_USE_BERSERK	"USE_BERSERK"
#define TALENT_XML_VALUE_EXTRAPASSIVE_FOCUS_USE_COUNTER	"USE_COUNTER"
#define TALENT_XML_VALUE_EXTRAPASSIVE_FOCUS_BERSERK_DECREASE_MAXBUBBLE	"BERSERK_DECREASE_MAXBUBBLE"
#define TALENT_XML_VALUE_EXTRAPASSIVE_FOCUS_BERSERK_EXTENDTIME	"BERSERK_EXTENDTIME"
#define TALENT_XML_VALUE_EXTRAPASSIVE_FOCUS_COUNTER_EXTENDTIME	"COUNTER_EXTENDTIME"
#define TALENT_XML_VALUE_EXTRAPASSIVE_FOCUS_ADVENT_EXTENDTIME	"ADVENT_EXTENDTIME"

#define TALENT_XML_VALUE_EXTRAPASSIVE_3COMBO			"3COMBO"
#define TALENT_XML_VALUE_EXTRAPASSIVE_SWORD_DRAWING		"SWORD_DRAWING"
#define TALENT_XML_VALUE_EXTRAPASSIVE_QUICK_RISE		"QUICK_RISE"
#define TALENT_XML_VALUE_EXTRAPASSIVE_QUICK_DRAW		"QUICK_DRAW"
#define TALENT_XML_VALUE_EXTRAPASSIVE_UPPERCUT			"UPPERCUT"
#define TALENT_XML_VALUE_EXTRAPASSIVE_RISING_ATTACK		"RISING_ATTACK"
#define TALENT_XML_VALUE_EXTRAPASSIVE_GUARD				"GUARD"
#define TALENT_XML_VALUE_EXTRAPASSIVE_COUNTER			"COUNTER"
#define TALENT_XML_VALUE_EXTRAPASSIVE_MAGICAL_DYNAMICS	"MAGICAL_DYNAMICS"
#define TALENT_XML_VALUE_EXTRAPASSIVE_ITEM_THROWING		"ITEM_THROWING"
#define TALENT_XML_VALUE_EXTRAPASSIVE_ITEM_TRAP			"ITEM_TRAP"

#define TALENT_XML_VALUE_EXTRAACTIVE_PORTAL				"PORTAL"
#define TALENT_XML_VALUE_EXTRAACTIVE_PORTAL_SOULBINDING	"PORTAL_SOULBINDING"


#define TALENT_XML_VALUE_EXTRAACTIVE_REVIVE				"REVIVE"
#define TALENT_XML_VALUE_EXTRAACTIVE_TAUNT				"TAUNT"

#define TALENT_XML_VALUE_EXTRAACTIVE_CHANGE_TO_STATE_COMBAT				"TO_STA_COMBAT"
#define TALENT_XML_VALUE_EXTRAACTIVE_BUFF_ENTITY						"BUFF_ENTITY"
#define TALENT_XML_VALUE_EXTRAACTIVE_SPAWN								"SPAWN"
#define TALENT_XML_VALUE_EXTRAACTIVE_NPC_ONLY_GRAPPLE					"GRAPPLE"
#define TALENT_XML_VALUE_EXTRAACTIVE_NPC_ONLY_EAT						"EAT"
#define TALENT_XML_VALUE_EXTRAACTIVE_TOGGLE_PRECISION					"TOGGLE_PRECISION"
#define TALENT_XML_VALUE_EXTRAACTIVE_TOGGLE_SNEAK						"TOGGLE_SNEAK"
#define TALENT_XML_VALUE_EXTRAACTIVE_ADVENT								"ADVENT"

#define TALENT_XML_VALUE_EXTRAACTIVE_DISPEL				"DISPEL"
#define TALENT_XML_VALUE_EXTRAACTIVE_CURE_POISON		"CURE_POISON"
#define TALENT_XML_VALUE_EXTRAACTIVE_CURE_DISEASE		"CURE_DISEASE"
#define TALENT_XML_VALUE_EXTRAACTIVE_CURE_CURSE			"CURE_CURSE"
#define TALENT_XML_VALUE_EXTRAACTIVE_DISPEL_MESMERIZE	"DISPEL_MESMERIZE"
#define TALENT_XML_VALUE_EXTRAACTIVE_DISPEL_DEATHPENALTY	"DISPEL_DEATHPENALTY"
#define TALENT_XML_VALUE_EXTRAACTIVE_DISPEL_BUFF		"DISPEL_BUFF"
#define TALENT_XML_VALUE_EXTRAACTIVE_DISPEL_FOCUS		"DISPEL_FOCUS"
#define TALENT_XML_VALUE_EXTRAACTIVE_DISPEL_BPART		"DISPEL_BPART"

#define TALENT_XML_VALUE_CATEGORY_COMMON				"common"
#define TALENT_XML_VALUE_CATEGORY_MELEE					"melee"
#define TALENT_XML_VALUE_CATEGORY_RANGE					"range"
#define TALENT_XML_VALUE_CATEGORY_MAGIC					"magic"

#define TALENT_XML_VALUE_DMGTYPE_PHYS					"physic"
#define TALENT_XML_VALUE_DMGTYPE_MAG					"magic"

#define TALENT_XML_VALUE_SKILLTYPE_NONE					"none"
#define TALENT_XML_VALUE_SKILLTYPE_MELEE				"melee"
#define TALENT_XML_VALUE_SKILLTYPE_ARCHERY				"archery"
#define TALENT_XML_VALUE_SKILLTYPE_GUN					"gun"
#define TALENT_XML_VALUE_SKILLTYPE_MAGIC				"magic"
#define TALENT_XML_VALUE_SKILLTYPE_GUARD				"guard"
#define TALENT_XML_VALUE_SKILLTYPE_PASSIVE				"passive"
#define TALENT_XML_VALUE_SKILLTYPE_EXTRA_ACTIVE			"extra_active"
#define TALENT_XML_VALUE_SKILLTYPE_EXTRA_PASSIVE		"extra_passive"
#define TALENT_XML_VALUE_SKILLTYPE_SOCIAL				"social"
#define TALENT_XML_VALUE_SKILLTYPE_ITEM					"item"

#define TALENT_XML_VALUE_CRAFTTYPE_NONE					"none"
#define TALENT_XML_VALUE_CRAFTTYPE_MARMOR				"marmor"
#define TALENT_XML_VALUE_CRAFTTYPE_HARMOR				"harmor"
#define TALENT_XML_VALUE_CRAFTTYPE_WEAPON				"weapon"
#define TALENT_XML_VALUE_CRAFTTYPE_CLOTH				"cloth"
#define TALENT_XML_VALUE_CRAFTTYPE_LEATHER				"leather"
#define TALENT_XML_VALUE_CRAFTTYPE_JEWELY				"jewely"
#define TALENT_XML_VALUE_CRAFTTYPE_WOOD					"wood"
#define TALENT_XML_VALUE_CRAFTTYPE_COOKING				"cooking"
#define TALENT_XML_VALUE_CRAFTTYPE_ALCHEMY				"alchemy"

#define TALENT_XML_VALUE_FOCUS_COUNTER					"Counter"
#define TALENT_XML_VALUE_FOCUS_BERSERK					"Berserk"
#define TALENT_XML_VALUE_FOCUS_SNEAK					"Sneak"
#define TALENT_XML_VALUE_FOCUS_PRECISION				"Precision"
#define TALENT_XML_VALUE_FOCUS_ENLIGHTEN				"Enlighten"
#define TALENT_XML_VALUE_FOCUS_ADVENT					"Advent"

#define TALENT_XML_VALUE_FINISH_EFFECT_NONE				"none"
#define TALENT_XML_VALUE_FINISH_EFFECT_BPARTS			"bparts"
#define TALENT_XML_VALUE_FINISH_EFFECT_THROWUP			"throwup"
#define TALENT_XML_VALUE_FINISH_EFFECT_KNOCKBACK		"knockback"
#define TALENT_XML_VALUE_FINISH_EFFECT_RANDOM			"random"
#define TALENT_XML_VALUE_FINISH_EFFECT_THROWUP_BPARTS	"throwup_bparts"
#define TALENT_XML_VALUE_FINISH_EFFECT_KNOCKBACK_BPARTS	"knockback_bparts"
#define TALENT_XML_VALUE_FINISH_EFFECT_RANDOM_BPARTS	"random_bparts"

#define TALENT_XML_VALUE_MOVING_USE_TYPE_NONE			"none"
#define TALENT_XML_VALUE_MOVING_USE_TYPE_CASTING		"casting"
#define TALENT_XML_VALUE_MOVING_USE_TYPE_USE			"use"
#define TALENT_XML_VALUE_MOVING_USE_TYPE_ALL			"all"

//////////////////////////////////////////////////////////////////////////
#define TALENT_XML_VALUE_BUFF_CONDITION_NONE				"none"
#define TALENT_XML_VALUE_BUFF_CONDITION_USE_THIS_TALENT		"use_this_talent"
#define TALENT_XML_VALUE_BUFF_CONDITION_FINISH_THIS_TALENT	"finish_this_talent"
#define TALENT_XML_VALUE_BUFF_CONDITION_GAIN				"gain"
#define TALENT_XML_VALUE_BUFF_CONDITION_GONE				"gone"
#define TALENT_XML_VALUE_BUFF_CONDITION_DISPELLED			"dispelled"
#define TALENT_XML_VALUE_BUFF_CONDITION_EXPIRED				"expired"
#define TALENT_XML_VALUE_BUFF_CONDITION_PERIOD				"period"
#define TALENT_XML_VALUE_BUFF_CONDITION_GAIN_N_PERIOD		"gain_and_period"
#define TALENT_XML_VALUE_BUFF_CONDITION_HIT_SUCCUESS		"hit_success"
#define TALENT_XML_VALUE_BUFF_CONDITION_HIT_THIS_TALENT		"hit_this_talent"
#define TALENT_XML_VALUE_BUFF_CONDITION_HIT_ALL_THIS_TALENT	"hit_all_this_talent"
#define TALENT_XML_VALUE_BUFF_CONDITION_HIT_ME				"hit_me"
#define TALENT_XML_VALUE_BUFF_CONDITION_MISS_ME				"miss_me"
#define TALENT_XML_VALUE_BUFF_CONDITION_GUARD_ME			"guard_me"
#define TALENT_XML_VALUE_BUFF_CONDITION_PERFECT_GUARD_ME	"perfect_guard_me"
#define TALENT_XML_VALUE_BUFF_CONDITION_CRITICAL_HIT_ME		"crihit_me"
#define TALENT_XML_VALUE_BUFF_CONDITION_HIT_ENEMY			"hit"
#define TALENT_XML_VALUE_BUFF_CONDITION_MISS_ENEMY			"miss"
#define TALENT_XML_VALUE_BUFF_CONDITION_GUARD_ENEMY			"guard"
#define TALENT_XML_VALUE_BUFF_CONDITION_CRITICAL_HIT_ENEMY	"crihit"
#define TALENT_XML_VALUE_BUFF_CONDITION_COUNTER				"counter"
#define TALENT_XML_VALUE_BUFF_CONDITION_RESIST				"resist"
#define TALENT_XML_VALUE_BUFF_CONDITION_BUFF_HIT			"buff_hit"
#define TALENT_XML_VALUE_BUFF_CONDITION_BUFF_MAX_STACKED		"max_stack"
#define TALENT_XML_VALUE_BUFF_CONDITION_BUFF_STACKED		"stack"
#define TALENT_XML_VALUE_BUFF_CONDITION_HIT_ME_N			"hit_me_n"
#define TALENT_XML_VALUE_BUFF_CONDITION_CRIHIT_ME_N			"crihit_me_n"
#define TALENT_XML_VALUE_BUFF_CONDITION_DAMAGE				"damage"
#define TALENT_XML_VALUE_BUFF_CONDITION_AFFECTED			"affected"
#define TALENT_XML_VALUE_BUFF_CONDITION_MAGIC_ACT			"magic_act"
#define TALENT_XML_VALUE_BUFF_CONDITION_MAGIC_HIT_ME		"magic_hit_me"
#define TALENT_XML_VALUE_BUFF_CONDITION_MAGIC_HIT_ENEMY		"magic_hit"
#define TALENT_XML_VALUE_BUFF_CONDITION_MELEE_HIT_ME		"melee_hit_me"
#define TALENT_XML_VALUE_BUFF_CONDITION_MELEE_HIT_ENEMY		"melee_hit"
#define TALENT_XML_VALUE_BUFF_CONDITION_DO_SOMETHING		"do_something"

#define TALENT_XML_VALUE_TO_MODE0							"TO_MODE0"
#define TALENT_XML_VALUE_TO_MODE1							"TO_MODE1"
#define TALENT_XML_VALUE_TO_MODE2							"TO_MODE2"
#define TALENT_XML_VALUE_TO_MODE3							"TO_MODE3"
#define TALENT_XML_VALUE_TO_MODE4							"TO_MODE4"
#define TALENT_XML_VALUE_TO_MODE5							"TO_MODE5"
#define TALENT_XML_VALUE_TO_MODE6							"TO_MODE6"
#define TALENT_XML_VALUE_TO_MODE7							"TO_MODE7"
#define TALENT_XML_VALUE_TO_MODE8							"TO_MODE8"
#define TALENT_XML_VALUE_TO_MODE9							"TO_MODE9"
#define TALENT_XML_VALUE_TO_MODE10							"TO_MODE10"


#define TALENT_XML_VALUE_TARGETING_TYPE_STICKY				"sticky"
#define TALENT_XML_VALUE_TARGETING_TYPE_LINE				"line"
#define TALENT_XML_VALUE_TARGETING_TYPE_GROUND				"ground"



//////////////////////////////////////////////////////////////////////////

#define TALENT_XML_TAG_REQUIRE				"REQUIRE"
#define TALENT_XML_TAG_EFFECT				"EFFECT"
#define TALENT_XML_ATTR_ID					"id"
#define TALENT_XML_ATTR_MODE				"Mode"



#define TALENT_XML_ATTR_VALUE				"value"


#define TALENT_XML_ATTR_HP_COST				"HPCost"
#define TALENT_XML_ATTR_EN_COST				"ENCost"
#define TALENT_XML_ATTR_STA_COST			"STACost"
#define TALENT_XML_ATTR_CASTING_ANI			"CastingAni"
#define TALENT_XML_ATTR_CASTING_TIME		"CastingTime"
#define TALENT_XML_ATTR_USE_ANI				"UseAni"
#define TALENT_XML_ATTR_EXTRA_ACT_ANI		"ExtraAni"
#define TALENT_XML_ATTR_EXTRA_ACT_ANI_2		"ExtraAni2"
#define TALENT_XML_ATTR_EXTRA_ACT_ANI_3		"ExtraAni3"

#define TALENT_XML_ATTR_LUA_START			"Lua_OnStart"
#define TALENT_XML_ATTR_LUA_ACT				"Lua_OnAct"
#define TALENT_XML_ATTR_LUA_DELAYED_ACT		"Lua_OnDelayedAct"
#define TALENT_XML_ATTR_LUA_FINISH			"Lua_OnFinish"
#define TALENT_XML_ATTR_LUA_CANCEL			"Lua_OnCancel"

#define TALENT_XML_ATTR_RESIST_METHOD		"ResistMethod"
#define TALENT_XML_ATTR_RESIST_TYPE			"ResistType"
#define TALENT_XML_ATTR_RESIST_DIFFICULTY	"ResistDifficulty"
#define TALENT_XML_ATTR_CRITICAL_ENABLE		"CriticalEnable"
#define TALENT_XML_ATTR_DRAIN_RATE			"DrainRate"
#define TALENT_XML_ATTR_DRAIN_TYPE			"DrainType"

#define TALENT_XML_ATTR_CATEGORY			"Category"
#define TALENT_XML_ATTR_MIN_DAMAGE			"MinDamage"
#define TALENT_XML_ATTR_MAX_DAMAGE			"MaxDamage"
#define TALENT_XML_ATTR_MIN_HEAL			"MinHeal"
#define TALENT_XML_ATTR_MAX_HEAL			"MaxHeal"
#define TALENT_XML_ATTR_WEAPON_APPLY_RATE	"WeaponApplyRate"
#define TALENT_XML_ATTR_WEAPON_REFRENCE		"WeaponReference"
#define TALENT_XML_ATTR_CRITICAL_APPLY_RATE	"CriticalApplyRate"
#define TALENT_XML_ATTR_DAMAGE_ATTRIB		"DamageAttrib"
#define TALENT_XML_ATTR_PROJECTILE_TYPE		"ProjectileType"
#define TALENT_XML_ATTR_PROJECTILE_ART		"ProjectileArt"
#define TALENT_XML_ATTR_PROJECTILE_SPEED	"ProjectileSpeed"
#define TALENT_XML_ATTR_RANGE				"Range"


#define TALENT_XML_ATTR_PROJECTILE_HIT_RADIUS	"ProjectileHitRadius"
#define TALENT_XML_ATTR_HATE_ADJ			"HateAdj"
#define TALENT_XML_ATTR_HATE_FACTOR			"HateFactor"
#define TALENT_XML_ATTR_EFFECT_TIMING		"EffectTiming"

#define TALENT_XML_ATTR_INVINCIBLE_TIME_START	"InvincibleTimeStart"
#define TALENT_XML_ATTR_INVINCIBLE_TIME_END		"InvincibleTimeEnd"
#define TALENT_XML_ATTR_SUPERARMOR_TIME_START	"SuperarmorTimeStart"
#define TALENT_XML_ATTR_SUPERARMOR_TIME_END		"SuperarmorTimeEnd"
#define TALENT_XML_ATTR_AVOIDABLE				"Avoidable"
#define TALENT_XML_ATTR_AVOID_TIME_START		"AvoidTimeStart"
#define TALENT_XML_ATTR_AVOID_TIME_END			"AvoidTimeEnd"
#define TALENT_XML_ATTR_POST_DELAY				"NPC_PostDelay"
#define TALENT_XML_ATTR_AVAILABLE_ON_GUARD		"AvailableOnGuard"

#define TALENT_XML_ATTR_IS_MOVING			"NPC_IsMoving"
#define TALENT_XML_ATTR_IS_SET_DIRECTION	"NPC_IsSetDirection"
#define TALENT_XML_ATTR_KEEP_INCLUDEBUFF			"NPC_KeepInclude"
#define TALENT_XML_ATTR_KEEP_EXCLUDEBUFF			"NPC_KeepExclude"
#define TALENT_XML_ATTR_NPC_INCLUDE			"NPC_Include"
#define TALENT_XML_ATTR_NPC_EXCLUDE			"NPC_Exclude"

#define TALENT_XML_ATTR_HIT_DELAY			"HitDelay"
#define TALENT_XML_ATTR_SEPARATE_HIT		"SeparateHit"
#define TALENT_XML_ATTR_HIT_POS_SYNC		"HitPosSync"

#define TALENT_XML_ATTR_FORCE_MF			"FORCE_MF"
#define TALENT_XML_ATTR_FORCE_MF_WEIGHT		"FORCE_MF_WEIGHT"

// 일단 판정 테스트용
#define TALENT_XML_ATTR_HIT_START_TIME		"Area2StartTime"
#define TALENT_XML_ATTR_HIT_DURATION_TIME	"Area2DurationTime"
#define TALENT_XML_ATTR_HIT_SIZE				"Area2Size"
#define TALENT_XML_ATTR_HIT_POSITION_X		"Area2PosX"
#define TALENT_XML_ATTR_HIT_POSITION_Y		"Area2PosY"
#define TALENT_XML_ATTR_HIT_POSITION_Z		"Area2PosZ"

#define TALENT_XML_ATTR_VALIDATION			"validation"




#define TALENT_XML_VALUE_PROJECTILETYPE_MISSILE			"missile"
#define TALENT_XML_VALUE_PROJECTILETYPE_GUIDED			"guided"
#define TALENT_XML_VALUE_PROJECTILETYPE_HITCAPSULE_GUIDED			"hitcapsule_guided"
#define TALENT_XML_VALUE_EFFICACYTYPE_ACTOR				"actor"
#define TALENT_XML_VALUE_EFFICACYTYPE_AREA				"area "


#define TALENT_XML_VALUE_FRONT							"front"
#define TALENT_XML_VALUE_BACK							"back"
#define TALENT_XML_VALUE_ALL							"all"

#define TALENT_XML_VALUE_RESIST_BINARY					"binary"
#define TALENT_XML_VALUE_RESIST_PARTIAL					"partial"

#define TALENT_XML_VALUE_RESIST_FR						"FR"
#define TALENT_XML_VALUE_RESIST_CR						"CR"
#define TALENT_XML_VALUE_RESIST_PR						"PR"
#define TALENT_XML_VALUE_RESIST_LR						"LR"
#define TALENT_XML_VALUE_RESIST_HR						"HR"
#define TALENT_XML_VALUE_RESIST_UR						"UR"
#define TALENT_XML_VALUE_RESIST_CHA						"CHA"


#define TALENT_XML_TAG_TALENT_INFO						"TALENT_INFO"

// Talent_EXT
#define TALENT_XML_VALUE_TYPE							"type"
#define TALENT_XML_TAG_EVENTS							"Events"
#define TALENT_XML_TAG_PROJECTILE						"Projectile"
#define TALENT_XML_TAG_ACTANITIME						"ActAniTime"
#define TALENT_XML_ATTR_EXTRA_TIME						"extra_time"
#define TALENT_XML_ATTR_EXTRA_TIME2						"extra_time2"
#define TALENT_XML_ATTR_EXTRA_TIME3						"extra_time3"
#define TALENT_XML_ATTR_ACT_ANIMATION_TIME				"act_animation_time"
#define TALENT_XML_ATTR_REFERENCE_ID					"reference_id"
#define TALENT_XML_ATTR_REFERENCE_MODE					"reference_mode"

#define TALENT_XML_ATTR_TAG_EVENT						"Event"
#define TALENT_XML_ATTR_TAG_NOMAL						"Normal"
#define TALENT_XML_ATTR_TAG_ACT							"Act"
#define TALENT_XML_ATTR_TAG_START_POS					"StartPos"
#define TALENT_XML_ATTR_TAG_WEAPONTYPE					"weapontype"

#define TALENT_XML_VALUE_TALENTEVENTTYPE_NONE			"none"
#define TALENT_XML_VALUE_TALENTEVENTTYPE_FIRE_EFFECT	"fire"
#define TALENT_XML_VALUE_TALENTEVENTTYPE_PROJECTILE		"projectile"
#define TALENT_XML_VALUE_TALENTEVENTTYPE_EFFECT			"effect"
#define TALENT_XML_VALUE_TALENTEVENTTYPE_SOUND			"sound"
#define TALENT_XML_VALUE_TALENTEVENTTYPE_CAMERA			"camera"
#define TALENT_XML_VALUE_TALENTEVENTTYPE_DAMAGE			"damage"
#define TALENT_XML_VALUE_TALENTEVENTTYPE_CUSTOM			"sh_custom"
#define TALENT_XML_VALUE_TALENTEVENTTYPE_DELAYED_ACT	"delayed_act"
#define TALENT_XML_VALUE_TALENTEVENTTYPE_EXTRAACTIVE_1	"extra_active_1"
#define TALENT_XML_VALUE_TALENTEVENTTYPE_EXTRAACTIVE_2	"extra_active_2"
#define TALENT_XML_VALUE_TALENTEVENTTYPE_CAMERA_LOCK	"camera_lock"
#define TALENT_XML_VALUE_TALENTEVENTTYPE_GROUND_FIRE_EFFECT	"ground_fire"

#define TALENT_XML_VALUE_TALENTEVENT_TIME				"time"
#define TALENT_XML_VALUE_TALENTEVENT_TIME2				"time2"
#define TALENT_XML_VALUE_TALENTEVENT_STR_CUSTOM_EVENT	"strCustomEvent"

#define TALENT_XML_VALUE_TALENTEVENT_STR_PARAM1			"strparam1"
#define TALENT_XML_VALUE_TALENTEVENT_STR_PARAM2			"strparam2"
#define TALENT_XML_VALUE_TALENTEVENT_INT_PARAM1			"intparam3"
#define TALENT_XML_VALUE_TALENTEVENT_INT_PARAM2			"intparam4"

#define TALENT_XML_VALUE_TALENTEVENT_LOCAL_X			"x"
#define TALENT_XML_VALUE_TALENTEVENT_LOCAL_Y			"y"

#define TALENT_XML_VALUE_TALENTEVENT_SERVER_DIR			"serverdir"

#define TALENT_XML_ATTR_TALENT_FOLLOW					"Follow"

#define TALENT_XML_ATTR_HITFILTER_MF_BEATEN			"BeatenHit"
#define TALENT_XML_ATTR_HITFILTER_MF_KNOCKBACK		"KnockbackHit"
#define TALENT_XML_ATTR_HITFILTER_MF_STUN			"StunHit"
#define TALENT_XML_ATTR_HITFILTER_MF_DEFLECT		"DeflectHit"
#define TALENT_XML_ATTR_HITFILTER_MF_THROWUP		"ThrowupHit"
#define TALENT_XML_ATTR_HITFILTER_MF_KNOCKDOWN		"KnockdownHit"
#define TALENT_XML_ATTR_HITFILTER_MF_UPPERED		"UpperedHit"

#define TALENT_XML_ATTR_HITFILTER_ALTITUDE_NORMAL	"NormalHit"
#define TALENT_XML_ATTR_HITFILTER_ALTITUDE_FLOATING	"FloatingHit"
#define TALENT_XML_ATTR_HITFILTER_ALTITUDE_SKY		"SkyHit"

#define TALENT_XML_TAG_CASTING_MOVE_SEGMENT				"CastingMoveSegment"
#define TALENT_XML_TAG_CASTINGLOOP_MOVE_SEGMENT			"CastingLoopMoveSegment"
#define TALENT_XML_TAG_MOVE_SEGMENT						"MoveSegment"
#define TALENT_XML_TAG_EXTRA_MOVE_SEGMENT				"ExtraMoveSegment"
#define TALENT_XML_TAG_EXTRA2_MOVE_SEGMENT				"Extra2MoveSegment"
#define TALENT_XML_TAG_EXTRA3_MOVE_SEGMENT				"Extra3MoveSegment"
#define TALENT_XML_TAG_POS								"Pos"
#define TALENT_XML_TAG_ROT								"Rot"

#define TALENT_XML_ATTR_TIME_INDEX						"TimeIndex"


// talent_ext.xml
#define TALENT_XML_ATTR_PROJECTILE_START_POS			"StartPos"
#define TALENT_XML_ATTR_PROJECTILE_MALE_START_POS		"MaleStartPos"

#define TALENT_XML_ATTR_PROJECTILE_START_X			"start_x"
#define TALENT_XML_ATTR_PROJECTILE_START_Y			"start_y"
#define TALENT_XML_ATTR_PROJECTILE_START_Z			"start_z"
#define TALENT_XML_ATTR_PROJECTILE_START_MALE_X		"male_start_x"
#define TALENT_XML_ATTR_PROJECTILE_START_MALE_Y		"male_start_y"
#define TALENT_XML_ATTR_PROJECTILE_START_MALE_Z		"male_start_z"

#define TALENT_XML_ATTR_TALENT_BONENAME				"BoneName"

#define TALENT_XML_VALUE_PROJECTILE_VISUAL_TYPE_STRAIGHT		"straight"
#define TALENT_XML_VALUE_PROJECTILE_VISUAL_TYPE_CURVE			"curve"
#define TALENT_XML_VALUE_PROJECTILE_VISUAL_TYPE_PARABOLA		"parabola"

#define TALENT_XML_ATTR_PROJECTILE_VISUAL_TYPE		"ProjectileVisualType"
#define TALENT_XML_ATTR_PROJECTILE_RANGE			"ProjectileRange"

#define TALENT_XML_ATTR_PROJECTILE_EFFECT_NAME				"ProjectileEffectName"
#define TALENT_XML_ATTR_PROJECTILE_ATTACK_EFFECT_NAME		"AttackEffectName"
#define TALENT_XML_ATTR_PROJECTILE_HITGROUND_EFFECT_NAME	"HitGroundEffectName"
#define TALENT_XML_ATTR_PROJECTILE_DEFENCE_EFFECT_NAME		"DefenceEffectName"
#define TALENT_XML_ATTR_PROJECTILE_FIRE_EFFECT_NAME			"FireEffectName"

#define TLAENT_XML_ATTR_PROJECTILE_SEGMENT_INDEX	"SegmentIndex"
#define TLAENT_XML_ATTR_PROJECTILE_CAPSULE_INDEX	"CapsuleIndex"


