#ifndef _CSWORLD_INFO_H
#define _CSWORLD_INFO_H


// 레이더즈의 시간대
enum GAME_TIME_TYPE
{
	TIME_INVALID = -1,
	TIME_DAWN = 0,			// 새벽
	TIME_DAYTIME,			// 낮
	TIME_SUNSET,			// 해질녘
	TIME_NIGHT,				// 밤
	TIME_CUSTOM1,
	TIME_CUSTOM2,
	MAX_TIME_TYPE
};

static const TCHAR* GAME_TIME_TYPE_NAME[] = 
{
	_T("TIME_DAWN"),
	_T("TIME_DAYTIME"),
	_T("TIME_SUNSET"),
	_T("TIME_NIGHT"),
	_T("TIME_CUSTOM1"),
	_T("TIME_CUSTOM2"),
};	

// 레이더즈의 날씨
enum GAME_WEATHER_TYPE
{
	WEATHER_INVALID = -1,
	WEATHER_SUNNY = 0,		// 맑음
	WEATHER_CLOUDY,			// 흐림
	WEATHER_RAINY,			// 비
	WEATHER_HEAVY_RAINY,	// 폭우
	WEATHER_SNOWY,			// 눈
	WEATHER_HEAVY_SNOWY,	// 폭설
	WEATHER_CUSTOM1,
	WEATHER_CUSTOM2,
	MAX_WEATHER_TYPE
};

static const TCHAR* GAME_WEATHER_TYPE_NAME[] = 
{
	_T("WEATHER_SUNNY"),
	_T("WEATHER_CLOUDY"),
	_T("WEATHER_RAINY"),
	_T("WEATHER_HEAVY_RAINY"),
	_T("WEATHER_SNOWY"),
	_T("WEATHER_HEAVY_SNOWY"),
	_T("WEATHER_CUSTOM1"),
	_T("WEATHER_CUSTOM2")
};	

#define DEFAULT_GAME_TIME		TIME_DAYTIME	// 기본 시간대
#define DEFAULT_GAME_WEATHER	WEATHER_SUNNY	// 기본 날씨

#define W_SUN	WEATHER_SUNNY
#define W_CLD	WEATHER_CLOUDY
#define W_RNY	WEATHER_RAINY
#define W_HRN	WEATHER_HEAVY_RAINY
#define W_SNW	WEATHER_SNOWY
#define W_HSW	WEATHER_HEAVY_SNOWY
//#define W_CLR	WEATHER_CLEAR

#define MAX_NORMAL_WEATHER_TYPE	WEATHER_CUSTOM1	// custom1, custom2는 평상시에 사용하지 않는다.


#endif // _CSWORLD_INFO_H