#pragma once

enum TRADEMARKET_EXCEPTION
{
	TRADEMARKET_EXCEPTION_PUTON_INVALID_SLOT_NUM,
	TRADEMARKET_EXCEPTION_PUTON_INVALID_ITEM_COUNT,
	TRADEMARKET_EXCEPTION_PUTON_DB_ERROR,
};

const int TRADEMARKET_ITEM_SEARCH_PAGE_SIZE = 15; // 물품거래소 아이템 검색 목록 한 페이지 크기