#include "StdAfx.h"
#include "GPlayerGameGuard.h"
#include "ggsrv26.h" // 게임가드
#include "GConfig.h"
#include "GCommandCenter.h"
#include "GGlobal.h"
#include "GServer.h"
#include "CCommandTable.h"
#include "GCommandCenter.h"
#include "GCommand.h"
#include "GGameGuard.h"
#include "GEntityPlayer.h"