#pragma once

using namespace System;

namespace RSManaged
{
	public __value enum RFORMAT {
		RFMT_NONE = 0,
		RFMT_RGB16,
		RFMT_ARGB32,
		RFMT_DXT1,
		RFMT_R32F,
		RFMT_D24S8,
		RFMT_D24X8,
		RFMT_D16,
		RFMT_L8,
		RFMT_INDEX16,
		RFMT_INDEX32,
		RFMT_END,
	};

	public __value enum RFILLMODE {	// wireframe ( triangle line ) , solid
		RFILL_WIRE,
		RFILL_SOLID
	};

	public __value enum RBLEND {		// Blending constants
		RBLEND_ZERO,
		RBLEND_ONE,
		RBLEND_SRCCOLOR,
		RBLEND_INVSRCCOLOR,
		RBLEND_DESTCOLOR,
		RBLEND_INVDESTCOLOR,
		RBLEND_SRCALPHA,
		RBLEND_INVSRCALPHA,
		RBLEND_DESTALPHA,
		RBLEND_INVDESTALPHA,
		RBLEND_SRCALPHASAT,
		RBLEND_BLENDFACTOR,
		RBLEND_INVBLENDFACTOR,

		RBLEND_NONE,
	};

	public __value enum RBLENDOP {		// Blending operation
		RBLENDOP_ADD,
		RBLENDOP_SUBTRACT,
		RBLENDOP_REVSUBTRACT,
		RBLENDOP_MIN,
		RBLENDOP_MAX,
	};

	public __value enum RCMPFUNC {		// depth compare function
		RCMP_NEVER,
		RCMP_LESS,
		RCMP_EQUAL,
		RCMP_LESSEQUAL,
		RCMP_GREATER,
		RCMP_NOTEQUAL,
		RCMP_GREATEREQUAL,
		RCMP_ALWAYS,
	};

	public __value enum RPRIMITIVETYPE {	// Primitive types
		RPT_POINTLIST,
		RPT_LINELIST,
		RPT_LINESTRIP,
		RPT_TRIANGLELIST,
		RPT_TRIANGLESTRIP,
		RPT_TRIANGLEFAN,
	};

	public __value enum RCULL {			// Culling
		RCULL_NONE,
		RCULL_CCW,
		RCULL_CW,
	};

	public __value enum RTEXTURESTAGESTATETYPE {	// stage state
		RTSS_COLOROP,
		RTSS_COLORARG1,
		RTSS_COLORARG2,
		RTSS_ALPHAOP,
		RTSS_ALPHAARG1,
		RTSS_ALPHAARG2,
		RTSS_BUMPENVMAT00,
		RTSS_BUMPENVMAT01,
		RTSS_BUMPENVMAT10,
		RTSS_BUMPENVMAT11,
		RTSS_TEXCOORDINDEX,
		RTSS_BUMPENVLSCALE,
		RTSS_BUMPENVLOFFSET,
		RTSS_TEXTURETRANSFORMFLAGS,
		RTSS_COLORARG0,
		RTSS_ALPHAARG0,
		RTSS_RESULTARG,
		RTSS_CONSTANT,
	};

	public __value enum RTEXTUREOP {			// texture operation
		RTOP_DISABLE,
		RTOP_SELECTARG1,
		RTOP_SELECTARG2,
		RTOP_MODULATE,
		RTOP_MODULATE2X,
		RTOP_MODULATE4X,
		RTOP_ADD,
		RTOP_ADDSIGNED,
		RTOP_ADDSIGNED2X,
		RTOP_SUBTRACT,
		RTOP_ADDSMOOTH,
		RTOP_BLENDDIFFUSEALPHA,
		RTOP_BLENDTEXTUREALPHA,
		RTOP_BLENDFACTORALPHA,
		RTOP_BLENDTEXTUREALPHAPM,
		RTOP_BLENDCURRENTALPHA,
		RTOP_PREMODULATE,
		RTOP_MODULATEALPHA_ADDCOLOR,
		RTOP_MODULATECOLOR_ADDALPHA,
		RTOP_MODULATEINVALPHA_ADDCOLOR,
		RTOP_MODULATEINVCOLOR_ADDALPHA,
		RTOP_BUMPENVMAP,
		RTOP_BUMPENVMAPLUMINANCE,
		RTOP_DOTPRODUCT3,
		RTOP_MULTIPLYADD,
		RTOP_LERP,
	};

	public __value enum RSTENCILOP {			// stencil operation
		RSTENCILOP_KEEP = 0,
		RSTENCILOP_ZERO,
		RSTENCILOP_REPLACE,
		RSTENCILOP_INCRSAT,
		RSTENCILOP_DECRSAT,
		RSTENCILOP_INVERT,
		RSTENCILOP_INCR,
		RSTENCILOP_DECR,
	};

	public __value enum RTEXTUREADDRESS {		// texture address
		RTADDRESS_WRAP = 0,
		RTADDRESS_MIRROR,
		RTADDRESS_CLAMP,
		RTADDRESS_BORDER,
		RTADDRESS_MIRRORONCE,
	};

	public __value enum RRENDERPASS {
		RRP_NONE = -1,
		RRP_SKYBOX = 0,
		RRP_NORMAL,
		RRP_LIGHTMULTIPASS,
		RRP_SPOTLIGHT,
		RRP_STENCILLIGHT,
		RRP_PARTICLE,
		RRP_AFTEREFFECT,
		RRP_2D,

		RRP_MAX
	};


	public __value enum RQUERYFEATURETYPE {
		RQF_HARDWARETNL=0,
		RQF_USERCLIPPLANE,
		RQF_WFOG,
		RQF_VS11,
		RQF_VS20,
		RQF_PS10,
		RQF_PS11,
		RQF_PS20,
	};

	public __value enum RTEXTUREFILTERTYPE {
		RTF_POINT=0,
		RTF_LINEAR,
		RTF_BILINEAR,
		RTF_TRILINEAR,
		RTF_BILINEAR_ANISO,
		RTF_TRILINEAR_ANISO,
	};

	public __value enum RSETTRANSFORMTYPE {
		RST_WORLD = 0,
		RST_VIEW,
		RST_PROJECTION,
		RST_TEXTURE0,
		RST_TEXTURE1,
		RST_TEXTURE2,
		RST_TEXTURE3,
		RST_MAX
	};

	public __value enum RAniPartsMode 
	{
		AMode_All = 0,		// 전부
		AMode_Upper ,		// 상체
		AMode_Lower ,		// 하체
		AMode_ArmLeft,		// 왼쪽 팔
		AMode_ArmRight,		// 오른쪽 팔
		AMode_LegLeft,		// 왼쪽 다리
		AMode_LegRight,		// 오른쪽 다리
		AMode_End,
	};

}