#include "StdAfx.h"
#include "ZPMSObject.h"
#include "PMPMSConnector.h"
#include "PmRegionStat.h"
#include "MLocale.h"
#include "ZCommandCenter.h"
#include "CCommandTable_Master.h"
#include "MLocale.h"