#ifndef SDBT_DBTYPE_GAMEDB_H
#define SDBT_DBTYPE_GAMEDB_H


enum SDBT_DBTYPE
{
	SDBT_DBTYPE_NONE				= 0,
	SDBT_DBTYPE_ACCOUNTDB			= 1,
	SDBT_DBTYPE_GAMEDB				= 11,
	SDBT_DBTYPE_GAMEDB_SELECT_CHAR	= 12,
	SDBT_DBTYPE_LOGDB				= 21,
};


#endif