#ifndef _SDBTASKID_H
#define _SDBTASKID_H

enum SDBTASK_ID
{
	  SDBTID_NONE = 0

	, SDBTID_QUERY
	, SDBTID_QUERYITER

	, SDBTID_DEVELOP
	, SDBTID_SERVERGETSTATUS

	, SDBTID_LOGIN
	, SDBTID_LOGOUT

	, SDBTID_EFF_REMAIN_TIME_INSERT
	, SDBTID_TALENT_COOL_TIME_UPDATE_ALL
	, SDBTID_BUFF_REMAIN_EFFECT_UPDATE_ALL

	, SDBTID_ACCOUNTINSERT
	, SDBTID_ACC_UPDATE_CREATE_DT

	, SDBTID_CHARADDMONEY
	, SDBTID_CHARDELETE
	, SDBTID_CHARGETLOOKLIST
	, SDBTID_CHARINSERT
	, SDBTID_CHARMINUSMONEY
	, SDBTID_CHARSERIALIZE
	, SDBTID_CHARDIE
	, SDBTID_CHARUPDATEPLAYERGRADE
	, SDBTID_CHARLEVELUP
	, SDBTID_CHARLOOTMONEY
	, SDBTID_CHAR_INC_MONEY
	, SDBTID_CHAR_DEC_MONEY
	, SDBTID_CHAR_UPDATE_XP
	, SDBTID_CHAR_ENTER_FIELD
	, SDBTID_CHAR_UPDATE_TP

	, SDBTID_CRAFTINSERT
	, SDBTID_CRAFTUPDATE
	, SDBTID_CRAFT_RECPINSERT
	, SDBTID_CRAFT_RECPDELETE

	, SDBTID_CUTSCENESAWNINSERT

	, SDBTID_EMBLEMINSERT
	, SDBTID_EMBLEMSELECT

	, SDBTID_FACTIONINSERT
	, SDBTID_FACTIONUPDATE

	, SDBTID_GULDSERIALISE
	, SDBTID_GUILDINSERT
	, SDBTID_GUILDDELETE
	, SDBTID_GUILDMEMBERINSERT
	, SDBTID_GUILDMEMBERDELETE
	, SDBTID_GUILDMASTERCHANGE
	, SDBTID_GUILDUPDATESTORAGEMONEY

	, SDBTID_INSERTEXECCNT

	, SDBTID_ITEMBUYINSERT
	, SDBTID_ITEMBUYUPDATE
	, SDBTID_ITEMSELLDELETE
	, SDBTID_ITEMSELLUPDATE
	, SDBTID_ITEMSELLVERYCOMMON
	, SDBTID_ITEMLOOTINSERT
	, SDBTID_ITEMLOOTUPDATE
	, SDBTID_ITEMINSERT
	, SDBTID_ITEMREPAIR
	, SDBTID_ITEMREPAIR_ALL
	, SDBTID_ITEMLEARNTALENT
	, SDBTID_ITEMSPLIT
	, SDBTID_ITEMSWAPSLOT
	, SDBTID_ITEMMERGE	
	, SDBTID_ITEMUPDATE_STACKAMT
	, SDBTID_ITEM_INC_STACKAMT
	, SDBTID_ITEM_DEC_STACKAMT
	, SDBTID_ITEMDELETE
	, SDBTID_ITEMUPDATE_DURA
	, SDBTID_ITEM_EQUIP
	, SDBTID_ITEM_UNEQUIP
	, SDBTID_ITEM_ENCHANT
	, SDBTID_ITEM_DYE
	, SDBTID_ITEM_SORT
	
	, SDBTID_INNROOMREIST

	, SDBTID_PALETTEPUTUP
	, SDBTID_PALETTEDOWN
	, SDBTID_PALETTECHANGE

	, SDBTID_QUALIFYINSERT
	, SDBTID_QUALIFYDELETE

	, SDBTID_QUESTACCEPT
	, SDBTID_QUESTDONE
	, SDBTID_QUESTFAIL
	, SDBTID_QUESTGIVEUP
	, SDBTID_QUESTUPDATEOBJECT
	, SDBTID_QUESTUPDATEVAR
	, SDBTID_QUESTCOMPLETE
	, SDBTID_QUEST_PVP_REWARD_INVEN
	, SDBTID_QUEST_PVP_REWARD_MAIL

	, SDBTID_SOULBINDINGSAVE
	
	, SDBTID_CACHE_SYNC
	
	, SDBTID_TRADE

	, SDBTID_TALENTLEARN
	, SDBTID_TALENTRESET
	, SDBTID_TALENTRESETALL

	// 우편
	, SDBTID_MAIL_GET_LIST
	, SDBTID_MAIL_SEND
	, SDBTID_MAIL_CHECK_RCVR
	, SDBTID_MAIL_GET_CONTENT
	, SDBTID_MAIL_SET_READ
	, SDBTID_MAIL_DELETE
	, SDBTID_MAIL_GET_MONEY
	, SDBTID_MAIL_GET_ITEM

	, SDBTID_SERVER_INSERT
	, SDBTID_SERVER_START
	, SDBTID_SERVER_UPDATE

	, SDBTID_WORLD_INSERT
	, SDBTID_WORLD_UPDATE
	, SDBTID_WORLD_GET_LIST

	// 보관함
	, SDBTID_STORAGE_SERIALIZE
	, SDBTID_STORAGE_UPDATE_MONEY

	// 물품거래소
	, SDBTID_TRADEMARKET_PUTON

	, SDBTID_GUIDEBOOK_INSERT

	/////////////// 여기서 부터는 로그 //////////////////

	, SDBTID_LOG_START = 1000000000

	, SDBTID_CONN_LOG
	, SDBTID_CHAR_SELECT_LOG
	, SDBTID_DISCONN_LOG

	, SDBTID_NPC_KILLED_LOG

	, SDBTID_CHAR_USE_MONEY_LOG
	, SDBTID_CHAR_LOOT_MONEY_LOG
	, SDBTID_CHAR_XP_LOG
	, SDBTID_CHAR_LEVEL_UP_LOG	
	, SDBTID_CHAR_TRADE_LOG
	
	, SDBTID_ITEM_LOOT_LOG
	, SDBTID_ITEM_INSERT_LOG
	, SDBTID_ITEM_DELETE_LOG
	, SDBTID_ITEM_DEC_STACK_AMT_LOG
	, SDBTID_ITEM_BUY_LOG
	, SDBTID_ITEM_SELL_LOG
	, SDBTID_ITEM_SELL_VERY_COMON_LOG
	, SDBTID_ITEM_REPAIR_LOG
	, SDBTID_ITEM_ENCHANT_LOG
	, SDBTID_ITEM_DYE_LOG
	, SDBTID_ITEM_MERGE_AND_SPLIT_LOG
	, SDBTID_ITEM_MOVE_LOG

	, SDBTID_QUEST_ACCPET_LOG
	, SDBTID_QUEST_FAIL_LOG
	, SDBTID_QUEST_DONE_LOG
	, SDBTID_QUEST_COMPLETE_LOG
	, SDBTID_QUEST_ITEM_LOG
	, SDBTID_QPVP_LOG
	, SDBTID_QPVP_MAIL_LOG
	, SDBTID_QPVP_REWARD_ITEM_LOG

	, SDBTID_CRAFT_LOG
	, SDBTID_CRAFT_ITEM_LOG

	, SDBTID_GUILD_INSERT_LOG
	, SDBTID_GUILD_DELETE_LOG
	, SDBTID_GUILD_INSERT_MEMBER_LOG
	, SDBTID_GUILD_DELETE_MEMBER_LOG
	, SDBTID_GUILD_CHANGE_MASTER_LOG

	, SDBTID_GUILD_LOG
	, SDBTID_GUILD_MEMBER_LOG

	, SDBTID_TALENT_LEARN_LOG
	, SDBTID_TALENT_RESET_LOG
	, SDBTID_TALENT_RESET_ALL_LOG

	, SDBTID_ITEM_LEARN_TALENT_LOG

	, SDBTID_MAIL_WRITE_LOG
	, SDBTID_MAIL_GET_MONEY_LOG
	, SDBTID_MAIL_GET_ITEM_LOG
	, SDBTID_MAIL_DELETE_LOG

	, SDBTID_CBT_FILE_PLAYER_COUNT

	, SDBTID_PARTY_LOG
};


#endif