#ifndef _GDB_CODE_H
#define _GDB_CODE_H


class GDB_CODE
{
public :
	enum GAIN_ITEM
	{
		CD_L_MONEY_LOOT	= 301
	  , CD_L_ITEM_LOOT	= 302
	  , CD_L_MONEY_GAIN	= 303
	  , CD_L_ITEM_GAIN	= 304
	};

	enum MERGE_ITEM
	{
		CD_L_ITEM_MERGE_INVEN_TO_INVEN			= 802
	  , CD_L_ITEM_MERGE_INVEN_TO_CHAR_STORAGE	= 803
	  , CD_L_ITEM_MERGE_INVEN_TO_GUILD_STORAGE	= 804
	  , CD_L_ITEM_MERGE_CHAR_STORAGE_TO_INVEN	= 805
	  , CD_L_ITEM_MERGE_GUILD_STORAGE_TO_INVEN	= 806
	};

	enum SPLIT_ITEM
	{
		CD_L_ITEM_SPLIT_INVEN_TO_INVEN					= 2101
	  , CD_L_ITEM_SPLIT_INVEN_TO_CHAR_STORAGE			= 2102
	  , CD_L_ITEM_SPLIT_INVEN_TO_GUILD_STORAGE			= 2103
	  , CD_L_ITEM_SPLIT_CHAR_STORAGE_TO_CHAR_STORAGE	= 2014
	  , CD_L_ITEM_SPLIT_CHAR_STORAGE_TO_INVEN			= 2015
	  , CD_L_ITEM_SPLIT_GUILD_STORAGE_TO_GUILD_STORAGE	= 2016
	  , CD_L_ITEM_SPLIT_GUILD_STORAGE_TO_INVEN			= 2017
	};

	enum MOVE_ITEM
	{
		CD_L_ITEM_MOVE_INVEN_TO_INVEN			= 2001
  	  ,	CD_L_ITEM_MOVE_INVEN_TO_CHAR_STORAGE	= 2002
	  , CD_L_ITEM_MOVE_INVEN_TO_GUILD_STORAGE	= 2003
	  , CD_L_ITEM_MOVE_CHAR_STORAGE_TO_INVEN	= 2004
	  , CD_L_ITEM_MOVE_GUILD_STORAGE_TO_INVEN	= 2005
	};

	enum NPC_SHOP
	{
		CD_L_NPC_SHOP_BUY		= 401
	  , CD_L_NPC_SHOP_SELL		= 402
	  , CD_L_NPC_SHOP_SELL_VC	= 403
	  , CD_L_NPC_SHOP_REPAIR	= 404
	};

	enum USE
	{
		CD_L_MONEY_USE			= 1301
	  , CD_L_ITEM_USE			= 1302
	  , CD_L_MONEY_GUILD_CREATE = 1303
	};

	enum CRAFT
	{
		CD_L_CRAFT_PRODUCT	= 701
	  , CD_L_CRAFT_RECIPE	= 702
	};

	enum MAIL
	{
		CD_L_MAIL_SEND	= 1201
	  , CD_L_MAIL_RECV	= 1202
	  , CD_L_MAIL_DEL	= 1203
	};

	enum MAIL_ITEM
	{
		CD_L_MAIL_POSTAGE		= 1501
	  , CD_L_MAIL_MONEY_ATTACH	= 1502
	  , CD_L_MAIL_ITEM_ATTACH	= 1503
	  , CD_L_MAIL_MONEY_GAIN	= 1504
	  , CD_L_MAIL_ITEM_GAIN		= 1505
	};

	enum QUEST
	{
		CD_L_QUEST_ACCEPT	= 502
	  , CD_L_QUEST_FAIL		= 503
	  , CD_L_QUEST_GIVEUP	= 504
	  , CD_L_QUEST_REWARD	= 505
	  , CD_L_QPVP_REWARD	= 506
	};

	enum QUEST_ITEM
	{
		CD_L_QACCEPT_MONEY_DEC		= 1601
	  , CD_L_QACCEPT_MONEY_GAIN		= 1602
	  , CD_L_QACCEPT_ITEM_DEL		= 1603
	  , CD_L_QACCEPT_ITEM_GAIN		= 1604
	  , CD_L_QGIVEUP_ITEM_DEL		= 1605
	  , CD_L_QREWARD_MONEY_GAIN		= 1606
	  , CD_L_QREWARD_ITEM_DEL		= 1607
	  , CD_L_QREWARD_ITEM_GAIN		= 1608
	  , CD_L_QPVP_REWARD_MONEY_GAIN = 1609
	  , CD_L_QPVP_REWARD_ITEM_GAIN	= 1610
	};

	enum XP
	{
		CD_L_KILL_NPC_GAIN_XP				= 1701
	  , CD_L_QREWARD_XP_GAIN				= 1702
	  , CD_L_QPVP_REWARD_XP_GAIN			= 1703
	  , CD_L_KILL_NPC_GAIN_XP_LEVEL_UP		= 1704
	  , CD_L_QREWARD_XP_GAIN_LEVEL_UP		= 1705
	  , CD_L_QPVP_REWARD_XP_GAIN_LEVEL_UP	= 1706
	};

	enum KILL
	{
		CD_L_KILL_NPC				= 1801
	  , CD_L_KILL_1ON1_PVP_PLAYER	= 1802
	  , CD_L_KILL_TEAM_PVP_PLAYER	= 1803
	  , CD_L_KILL_QPVP_PLAYER		= 1804
	  , CD_L_KILL_ARENA_PLAYER		= 1805
	};

	enum DIE
	{
		CD_L_DIE_BY_NPC				= 1901
	  , CD_L_DIE_BY_1ON1_PVP_PLAYER	= 1902
	  , CD_L_DIE_BY_TEAM_PVP_PLAYER	= 1903
	  , CD_L_DIE_BY_QPVP_PLAYER		= 1904
	  , CD_L_DIE_BY_ARENA_PLAYER	= 1905
	  , CD_L_SUICIDE				= 1906
	};

	enum GUILD
	{
		CD_L_GUILD_INSERT			= 71,
		CD_L_GUILD_DELETE			= 72,
		CD_L_GUILD_MEMBER_INSERT	= 73,
		CD_L_GUILD_MEMBER_DELETE	= 74,
		CD_L_GUILD_MEMBER_KICK_OFF	= 75,
		CD_L_GUILD_MASTER_CHANGE	= 76,
	};

	enum PARTY
	{
		CD_L_PARTY_CREATE			= 2001,
		CD_L_PARTY_ENTER			= 2002,
		CD_L_PARTY_LEAVE			= 2003,
		CD_L_PARTY_KICK_OFF			= 2004,
		CD_L_PARTY_CHANGE_LEADER	= 2005,
		CD_L_PARTY_DELETE			= 2006,
	};

	enum ENCHANT
	{
		CD_L_ENCH_SUCCESS			= 1001,
		CD_L_ENCH_FAIL				= 1002,
		CD_L_ENCH_STONE				= 1003,
		CD_L_ENCH_AGENT				= 1004,
	};
};


#endif