#ifndef _TQUESTDBMANAGER_H
#define _TQUESTDBMANAGER_H

#define QUEST_DB_VTABLE_QUESTID							"QuestID"
#define QUEST_DB_VTABLE_QUESTBASEINFO					"QuestBaseInfo"
#define QUEST_DB_VTABLE_QUESTPR							"QuestPR"

#define QUEST_DB_TABLE_QUEST_COLUMN_QID					"QID"
#define QUEST_DB_TABLE_QUEST_COLUMN_TITLE				"Title"
#define QUEST_DB_TABLE_QUEST_COLUMN_RAIDABLE			"RaidAble"
#define QUEST_DB_TABLE_QUEST_COLUMN_QA					"QA"
#define QUEST_DB_TABLE_QUEST_COLUMN_REPEATABLE			"Repeatable"
#define QUEST_DB_TABLE_QUEST_COLUMN_TYPE				"Type"
#define QUEST_DB_TABLE_QUEST_COLUMN_ZONEDESCRIPTION		"ZoneDescription"
#define QUEST_DB_TABLE_QUEST_COLUMN_ZONELIFETIME		"ZoneLifeTime"
#define QUEST_DB_TABLE_QUEST_COLUMN_HIDETHENEXTSTEP		"HideTheNextStep"
#define QUEST_DB_TABLE_QUEST_COLUMN_DESCRIPTION			"Description"
#define QUEST_DB_TABLE_QUEST_COLUMN_DEADLINE			"Deadline"
#define QUEST_DB_TABLE_QUEST_COLUMN_REGDATE				"RegDate"
#define QUEST_DB_TABLE_QUEST_COLUMN_PR_MINLEVEL			"PR_MinLevel"
#define QUEST_DB_TABLE_QUEST_COLUMN_PR_MAXLEVEL			"PR_MaxLevel"
#define QUEST_DB_TABLE_QUEST_COLUMN_PR_QUEST			"PR_Quest"
#define QUEST_DB_TABLE_QUEST_COLUMN_PR_UNCOMPLETEDQUEST	"PR_UncompletedQuest"
#define QUEST_DB_TABLE_QUEST_COLUMN_PR_ITEMID			"PR_ItemID"
#define QUEST_DB_TABLE_QUEST_COLUMN_PR_EQUIPITEM		"PR_EquipItem"
#define QUEST_DB_TABLE_QUEST_COLUMN_PR_RACE				"PR_Race"
#define QUEST_DB_TABLE_QUEST_COLUMN_PR_SEX				"PR_Sex"
#define QUEST_DB_TABLE_QUEST_COLUMN_PR_HaveFID			"PR_HaveFID"


#define QUEST_DB_TABLE_QUESTPRFACTION					"QuestPRFaction"
#define QUEST_DB_TABLE_QUESTPRFACTION_COLUMN_QRFID		"QRFID"
#define QUEST_DB_TABLE_QUESTPRFACTION_COLUMN_QID		"QID"
#define QUEST_DB_TABLE_QUESTPRFACTION_COLUMN_MINFACTION	"MinFaction"
#define QUEST_DB_TABLE_QUESTPRFACTION_COLUMN_MAXFACTION	"MaxFaction"
#define QUEST_DB_TABLE_QUESTPRFACTION_COLUMN_FID		"FID"


#define QUEST_DB_VTABLE_OOBJECTIVE						"OObjective"
#define QUEST_DB_VTABLE_UOBJECTIVE						"UObjective"
#define QUEST_DB_TABLE_OBJECTIVE_COLUMN_QID				"QID"
#define QUEST_DB_TABLE_OBJECTIVE_COLUMN_OID				"OID"
#define QUEST_DB_TABLE_OBJECTIVE_COLUMN_TITLE			"Title"
#define QUEST_DB_TABLE_OBJECTIVE_COLUMN_DESCRIPTION		"Description"
#define QUEST_DB_TABLE_OBJECTIVE_COLUMN_TYPE			"Type"
#define QUEST_DB_TABLE_OBJECTIVE_COLUMN_PARAM1			"Param1"
#define QUEST_DB_TABLE_OBJECTIVE_COLUMN_PARAM2			"Param2"


#endif //_TQUESTDBMANAGER_H